### ISSUE TITLE
Assertion tokens are causing test plan build to fail

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#1037]
In PR #1036, in assertions.csv for radio test plan, I attempted to specify assertion tokens:

~~~
{screenReader} switched from {readingMode} to {interactionMode}
~~~

It caused an error in the build. We need these tokens for the mode switching assertions.

**Comment by howard-e** [comment]
@mcking65 I've replied on #1036 with the formatting issue I noticed, which should allow it properly build with assertionTokens.

What I have also noticed, after testing my suggestion is that the functionality for tokenizing `assertionPhrase` wasn't included like it is for `assertionStatement`. This must have been an oversight when reading the [assertionPhrase spec](https://github.com/w3c/aria-at/wiki/Test-Format-Definition-V2#assertionphrase). So the assertionPhrase column will read with the generic fallback text as well when rendered on the pattern's page.

#1038 addresses this

**Comment by mcking65** [comment]
@howard-e, thank you for the resolution!! Back on track now.
