### ISSUE TITLE
Resolve conflicts in Safari testing for Navigate out of a radio group (Radio Group Example Using aria-activedescendant, Test 5 and 6, V24.03.12)

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#1051]
#### Test 5: Review Conflicts for "Navigate out of the start of a radio group"

Unexpected Behaviors for "Shift+Tab" Command:
    
    *   Tester mmoss recorded output "link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space." and noted no unexpected behavior.
    *   Tester jha11y recorded output "link, Navigate forwards from here, main" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech (Details: announced main landmark?, Impact: MODERATE)".
    *   Tester IsaDC recorded output " link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space." and noted no unexpected behavior.

#### Test 6: Review Conflicts for "Navigate out of the end of a radio group"

Unexpected Behaviors for "Tab" Command:
    
    *   Tester mmoss recorded output "link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space." and noted no unexpected behavior.
    *   Tester jha11y recorded output "link, Navigate backwards from here, main" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech (Details: main landmark announced, Impact: MODERATE)".
    *   Tester IsaDC recorded output " link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space." and noted no unexpected behavior.

## Test Setup

- Test File: [test-11-navOutEndRadioGroup-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/radiogroup-aria-activedescendant/test-11-navOutEndRadioGroup-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.4.1)
- Browser: Safari (Version 17)

**Comment by IsaDC** [comment]
The community group agreed to mark the impact of this issue as moderate. See [CG meeting minutes](https://www.w3.org/2024/04/18-aria-at-minutes.html) from April 18, 2024.
