### ISSUE TITLE
Resolve conflicts in Safari testing for Navigate backwards into a radio group (Radio Group Example Using aria-activedescendant, Tests 2 and 4 V24.03.12)

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#1052]
#### Test 2: Review Conflicts for "Navigate backwards into a radio group where no radio buttons are checked"

Unexpected Behaviors for "Shift+j (single quick key nav on)" Command:
    
    *   Tester mmoss recorded output "Run Test Setup dimmed button You are currently on a button. This item is dimmed." and noted "Reading cursor position changed in an unexpected manner (Details: Cursor moved forward to the dimmed Run Test Setup button, rather than backward to the last radio button in thre group., Impact: MODERATE)".
    *   Tester jha11y recorded output "Run Test Setup, dimmed, button" and noted "Reading cursor position changed in an unexpected manner (Details: focus moved to the run setup button which is the opposite of the intended direction, Impact: SEVERE)".
    *   Tester IsaDC recorded output " Run Test Setup dimmed button You are currently on a button. This item is dimmed." and noted "Reading cursor position changed in an unexpected manner (Details: The reading cursor move to an unrelated button., Impact: MODERATE)".

#### Test 4: Review Conflicts for "Navigate backwards into a radio group where the last radio button is checked"

Unexpected Behaviors for "Shift+j (single quick key nav on)" Command:
    
    *   Tester mmoss recorded output "Run Test Setup dimmed button You are currently on a button. This item is dimmed." and noted "Reading cursor position changed in an unexpected manner (Details: The cusor did not move to the last radio button in the group, and instead moved to the Run Test Setup button., Impact: MODERATE)".
    *   Tester jha11y recorded output "Run Test Setup, dimmed, button" and noted "Reading cursor position changed in an unexpected manner (Details: focus moved to the run setup button which is the opposite of the intended direction, Impact: SEVERE)".
    *   Tester IsaDC recorded output " Run Test Setup dimmed button You are currently on a button. This item is dimmed." and noted "Reading cursor position changed in an unexpected manner (Details: Reading cursor move to unrelated button., Impact: MODERATE)".

#### Test Setup

- Test File: [test-06-NavBackIntoRadioGroupWhereLastRadioChecked-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/radiogroup-aria-activedescendant/test-06-NavBackIntoRadioGroupWhereLastRadioChecked-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.4.1)
- Browser: Safari (Version 17)

**Comment by mcking65** [comment]
@IsaDC 

Could you please document resolution and close?

**Comment by IsaDC** [comment]
The community group agreed to mark the impact of this issue as severe. See [CG meeting minutes](https://www.w3.org/2024/04/18-aria-at-minutes.html) from April 18, 2024.
