### ISSUE TITLE
Outdated NVDA Bot responses: "Open a modal dialog" (Modal Dialog Example, Test 1, V24.05.02)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#1062]
## Description of Behavior

The bot is currently operating on an older version of NVDA, which is known to display several undesirable behaviors. These issues have been resolved in the latest version (2024.1). I recommend that we either execute the test plan manually or update the bot to the most recent version.

## Test Setup

- Test File: [test-03-openModalDialog-nvda.collected.html](https://aria-at.netlify.app/tests/modal-dialog/test-03-openModalDialog-nvda.collected.html)
- AT: NVDA (Version 2023.3.3)
- Browser: Chrome (Version 124)

**Comment by gnarf** [comment]
The backend was updated to use 2024.1 on May 9: https://github.com/bocoup/aria-at-automation-nvda-builds/releases/tag/2024.1

**Comment by mcking65** [comment]
Thank you for the update!
