### ISSUE TITLE
Feedback: "Open a modal dialog" (Modal Dialog Example, Test 3, V24.05.09)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#1069]
## Description of Behavior

VoiceOver only announced the role (web dialog) as part of the VoiceOver instruction/usage hint text.  Should that be considered for passing an assertion?

## Test Setup

- Test File: [test-03-openModalDialog-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/modal-dialog/test-03-openModalDialog-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.4.1)
- Browser: Safari (Version 17)

**Comment by IsaDC** [comment]
@jha11y  No, we don't take hints from the screen readers as part of the test results.

**Comment by mcking65** [comment]
@jha11y  is this resolved?

**Comment by mcking65** [comment]
Question resolved.
