### ISSUE TITLE
Conflicting VoiceOver test results: "Close a modal dialog" (Modal Dialog Example, Test 6, V24.05.09)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#1071]
## Description of Behavior

This is similar to the behavior where VoiceOver unnecessarily conveys the main landmark. We discussed this in the Link Test Plan, so my suggestion would be to resolve this conflict in the same way for consistency.

## Test Setup

- Test File: [test-06-closeModalDialog-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/modal-dialog/test-06-closeModalDialog-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.4.1)
- Browser: Safari (Version 17)

## Review Conflicts for "Close a modal dialog"

1.  ### Unexpected Behaviors for "Escape" Command
    
    *   Tester IsaDC recorded output "Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech (Details: VoiceOver unnecessary conveys the main landmark., Impact: MODERATE)".
    *   Tester jha11y recorded output "Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted no unexpected behavior.
2.  ### Unexpected Behaviors for "Control+Option+Space" Command
    
    *   Tester IsaDC recorded output " Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech (Details: VoiceOver unnecessary conveys the main landmark., Impact: MODERATE)".
    *   Tester jha11y recorded output "Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted no unexpected behavior.
3.  ### Unexpected Behaviors for "Space" Command
    
    *   Tester IsaDC recorded output " Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech (Details: VoiceOver unnecessary conveys the main landmark., Impact: MODERATE)".
    *   Tester jha11y recorded output "Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted no unexpected behavior.
4.  ### Unexpected Behaviors for "Enter" Command
    
    *   Tester IsaDC recorded output " Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech (Details: VoiceOver unnecessary conveys the main landmark., Impact: MODERATE)".
    *   Tester jha11y recorded output "Add Delivery Address button main You are currently on a button. To click this button, press Control-Option-Space." and noted no unexpected behavior.

**Comment by mcking65** [comment]
@IsaDC 

I think we can close this based on discussion in May 22 meeting.
