### ISSUE TITLE
Feedback: "Increment a slider by one step" (Color Viewer Slider, Test 4, V24.06.26)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#1087]
## Description of Behavior

I have not been able to reproduce this issue.

## Test Setup

- Test File: [test-11-incrementSliderByOneStep-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/horizontal-slider/test-11-incrementSliderByOneStep-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.5)
- Browser: Safari (Version 17)

## Review Conflicts for "Increment a slider by one step"

1.  ### Unexpected Behaviors for "Control+Option+Shift+Down Arrow, then Control+Option+Up Arrow" Command
    
    *   Tester IsaDC recorded output " 129" and noted no unexpected behavior.
    *   Tester jha11y recorded output "In slider 128" and noted "Other (Details: the visible value increased, but the incorrect value was announced, Impact: SEVERE)".
2.  ### Assertion Results for "Control+Option+Shift+Down Arrow, then Control+Option+Up Arrow" Command and "Value '129' is conveyed" Assertion
    
    *   Tester IsaDC recorded output " 129" and marked assertion as passing.
    *   Tester jha11y recorded output "In slider 128" and marked assertion as failing.
3.  ### Unexpected Behaviors for "Control+Option+Shift+Down Arrow, then Control+Option+Right Arrow" Command
    
    *   Tester IsaDC recorded output " 129" and noted no unexpected behavior.
    *   Tester jha11y recorded output "In slider 128" and noted "Other (Details: the visible value increased, but the incorrect value was announced, Impact: SEVERE)".
4.  ### Assertion Results for "Control+Option+Shift+Down Arrow, then Control+Option+Right Arrow" Command and "Value '129' is conveyed" Assertion
    
    *   Tester IsaDC recorded output " 129" and marked assertion as passing.
    *   Tester jha11y recorded output "In slider 128" and marked assertion as failing.

**Comment by mcking65** [comment]
I get the same results as Joe using macOS 14.5 and 
Safari 17.5. It's pretty bad. In fact, every time you switch from incrementing to decrementing, you get the wrong values reported.

**Comment by IsaDC** [comment]
Results match after rerunning the test on a different computer. Closing this issue.
