### ISSUE TITLE
Conflicting results for test 2 "Navigate backwards to a collapsed disclosure button" (Disclosure Navigation Menu Example, V24.07.31)

### ISSUE THREAD

**Issue by tactics2** [w3c/aria-at#1099]
## Test Setup

- Test File: [test-06-navBackToCollapsedDisclosureButton-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/disclosure-navigation/test-06-navBackToCollapsedDisclosureButton-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.5)
- Browser: Safari (Version 17)

## Review Conflicts for "Navigate backwards to a collapsed disclosure button"

1.  ### Unexpected Behaviors for "Shift+j (quick nav on)" Command
    
    *   Tester tactics2 recorded output "academics collapsed button" and noted no unexpected behavior.
    *   Tester IsaDC recorded output " Run Test Setup dimmed button You are currently on a button. This item is dimmed." and noted "Reading cursor position changed in an unexpected manner (Details: Cursor moved to the wrong control., Impact: SEVERE)".
2.  ### Assertion Results for "Shift+j (quick nav on)" Command and "Role 'button' is conveyed" Assertion
    
    *   Tester tactics2 recorded output "academics collapsed button" and marked assertion as passing.
    *   Tester IsaDC recorded output " Run Test Setup dimmed button You are currently on a button. This item is dimmed." and marked assertion as failing.
3.  ### Assertion Results for "Shift+j (quick nav on)" Command and "Name of the button, 'Academics', is conveyed" Assertion
    
    *   Tester tactics2 recorded output "academics collapsed button" and marked assertion as passing.
    *   Tester IsaDC recorded output " Run Test Setup dimmed button You are currently on a button. This item is dimmed." and marked assertion as failing.
4.  ### Assertion Results for "Shift+j (quick nav on)" Command and "State 'collapsed' is conveyed" Assertion
    
    *   Tester tactics2 recorded output "academics collapsed button" and marked assertion as passing.
    *   Tester IsaDC recorded output " Run Test Setup dimmed button You are currently on a button. This item is dimmed." and marked assertion as failing.

it appears IsaDC was not reloading the test page after each test, which is why the test button is reported as being dimmed. My results are accurate. I have triple checked them.

**Comment by IsaDC** [comment]
Closing this issue as the test plan is being rerun from scratch.
