### ISSUE TITLE
Feedback on Test Harness Feature Requirements

### ISSUE THREAD

**Issue by mfairchild365** [w3c/aria-at#11]
This is the issue to track feedback on https://github.com/w3c/aria-at/wiki/Test-Harness-Feature-Requirements

**Comment by mfairchild365** [comment]
From the 2019-10-16

* We might need a 'partial' value in addition to 'pass' and 'fail' for tests. This might be the result of data aggregation, and a tester will likely not need to mark something as 'partial'. For now, only let testers explicitly mark results as pass or fail. We can revisit later if needed.
* Testers: there may be other 'roles', such as test authors, reviewers, etc. However, for the prototype, we don't need different roles in the system.
* Data collection: we might need multiple data fields. For example, a field to describe failures in detail (beyond just an utterance), what key command caused the fail (perhaps just a text field).
* Other requirements: we need to be able to customize forms to be very screen reader friendly
* We need to define a test, for example: 
  * Test tile
  * The attributes that will be tested
  * Screen reader instructions
  * Etc.

**Comment by spectranaut** [comment]
I copied over some of this into the wiki page :)

**Comment by spectranaut** [comment]
this document served it's purpose.
