### ISSUE TITLE
Translate checkbox tests to csv files

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-at#110]
And then get ride of the "checkbox-gen" directory (probably delete the "checkbox" directory and then rename "checkbox-gen" to checkbox).

**Comment by mfairchild365** [comment]
@jongund and @spectranaut - I'm happy to do this if it hasn't already been started. Might need a few pointers though.

**Comment by jongund** [comment]
@mfairchild365 
Yohta has been working on converting the tests, should be a pull tomorrow, but they will need to be reviewed by you
