### ISSUE TITLE
Feedback: "Navigate backwards to a menu button" (Action Menu Button Example Using aria-activedescendant, Test 2, V24.08.08)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#1103]
## Description of Behavior

I think the third key stroke is incorrect. it says J (quick Nav on), but it should be Shift+j (quick nav on)

## Test Setup

- Test File: [test-06-navBackToMenuButton-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/menu-button-actions-active-descendant/test-06-navBackToMenuButton-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.6.1)
- Browser: Safari (Version 17)

**Comment by IsaDC** [comment]
Thank you @jha11y 
This issue has been addressed and fixed by #1102
