### ISSUE TITLE
VoiceOver Recorder Feedback: Start recording key has side effects on test 9 "Navigate to an item in a menu by typing a character" (Action Menu Button Example Using aria-activedescendant, V24.08.08)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#1104]
## Description of Behavior

When using the VoiceOver recorder, I'm getting slightly different results for some of these tests.

This test With Recorder "Action 2, menu item". With out Recorder "Action 2". Same for previous test.  VoiceOver focus seems to shift whe I press the record hotkey. When I run the test setup, programmatic focus is in the menu, but VoiceOver focus is not present. But once I press the hot key the whole menu gets VoiceOver focus and VoiceOver announces "Actions, menu, 4 items". This is before I press the actual keystroke I am testing ("a").

## Test Setup

- Test File: [test-22-navToItemMenuByTypingCharacter-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/menu-button-actions-active-descendant/test-22-navToItemMenuByTypingCharacter-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.6.1)
- Browser: Safari (Version 17)

**Comment by IsaDC** [comment]
Closing this issue as the Community Group decided to keep the human testers' results.
