### ISSUE TITLE
Conflicting results for test 5 "Request information about a collapsed disclosure button" (Disclosure Navigation Menu Example, V24.08.12)

### ISSUE THREAD

**Issue by tactics2** [w3c/aria-at#1113]
## Test Setup

- Test File: [test-35-reqInfoAboutCollapsedDisclosureButton-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/disclosure-navigation/test-35-reqInfoAboutCollapsedDisclosureButton-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.5)
- Browser: Safari (Version 17)

## Review Conflicts for "Request information about a collapsed disclosure button"

1.  ### Assertion Results for "Control+Option+F3" Command and "Role 'button' is conveyed" Assertion
    
    *   Tester tactics2 recorded output "No output was detected." and marked assertion as failing.
    *   Tester IsaDC recorded output " About collapsed button is in the VoiceOver cursor" and marked assertion as passing.
2.  ### Assertion Results for "Control+Option+F3" Command and "Name of the button, 'About', is conveyed" Assertion
    
    *   Tester tactics2 recorded output "No output was detected." and marked assertion as failing.
    *   Tester IsaDC recorded output " About collapsed button is in the VoiceOver cursor" and marked assertion as passing.
4.  ### Assertion Results for "Control+Option+F3" Command and "State 'collapsed' is conveyed" Assertion

    *   Tester tactics2 recorded output "No output was detected." and marked assertion as failing.
    *   Tester IsaDC recorded output " About collapsed button is in the VoiceOver cursor" and marked assertion as passing.

When test setup button is activated, focus moves to control and "about collapsed button" is announced. When the user then presses Control+Option+F3, nothing more is announced. 

5.  ### Unexpected Behaviors for "Control+Option+F4" Command
    
    *   Tester tactics2 recorded output "No output was detected." and noted no unexpected behavior.
    *   Tester IsaDC recorded output " no action available button has keyboard focus" and noted "Reading cursor position changed in an unexpected manner (Details: The button didn't received focus., Impact: SEVERE)".

**Comment by IsaDC** [comment]
Closing this issue because the lack of output was due to the function key setting on an external keyboard.
