### ISSUE TITLE
Conflicting results for test 6 "Request information about an expanded disclosure button" (Disclosure Navigation Menu Example, V24.08.12)

### ISSUE THREAD

**Issue by tactics2** [w3c/aria-at#1115]
## Test Setup

- Test File: [test-38-reqInfoAboutExpandedDisclosureButton-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/disclosure-navigation/test-38-reqInfoAboutExpandedDisclosureButton-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 14.5)
- Browser: Safari (Version 17)

## Review Conflicts for "Request information about an expanded disclosure button"

1.  ### Assertion Results for "Control+Option+F3" Command and "Role 'button' is conveyed" Assertion
    
    *   Tester tactics2 recorded output "No output was detected." and marked assertion as failing.
    *   Tester IsaDC recorded output " About expanded button is in the VoiceOver cursor" and marked assertion as passing.
2.  ### Assertion Results for "Control+Option+F3" Command and "Name of the button, 'About', is conveyed" Assertion
    
    *   Tester tactics2 recorded output "No output was detected." and marked assertion as failing.
    *   Tester IsaDC recorded output " About expanded button is in the VoiceOver cursor" and marked assertion as passing.
3.  ### Assertion Results for "Control+Option+F3" Command and "State 'expanded' is conveyed" Assertion
    
    *   Tester tactics2 recorded output "No output was detected." and marked assertion as failing.
    *   Tester IsaDC recorded output " About expanded button is in the VoiceOver cursor" and marked assertion as passing.
4.  ### Unexpected Behaviors for "Control+Option+F4" Command
    
    *   Tester tactics2 recorded output "No output was detected." and noted no unexpected behavior.
    *   Tester IsaDC recorded output " no action available button has keyboard focus" and noted "Reading cursor position changed in an unexpected manner (Details: The button didn't received keyboard focus., Impact: SEVERE)".

Issues are the same as with previous test. When either Control+Option+F3 or Control+Option+F4 are pressed after setup, nothing further happens or is announced.

**Comment by IsaDC** [comment]
Closing this issue because the lack of output was due to the function key setting on an external keyboard.
