### ISSUE TITLE
NVDA Bot Feedback: Human and Bot record different output for test "Activate a link in a dropdown" (Disclosure Navigation Menu Example, Test 15, V24.08.12)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#1121]
## Description of Behavior

The automated NVDA output for the Enter (Focus mode on) key test did not match the NVDA out put.  The Automated was "collapse" which seemed to be from another test.  The actual output was " Mythical University sample page content [line break] region".

## Test Setup

- Test File: [test-65-activateLinkDropdown-nvda.collected.html](https://aria-at.netlify.app/tests/disclosure-navigation/test-65-activateLinkDropdown-nvda.collected.html)
- AT: NVDA (Version 2023.3)
- Browser: Chrome (Version 127)

**Comment by IsaDC** [comment]
Closing this issue as the test plan is being rerun from scratch.
