### ISSUE TITLE
Feedback: "Activate a link in a dropdown" (Disclosure Navigation Menu Example, Test 14, V24.10.10)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#1146]
## Description of Behavior

NVDA bot output for Enter (focus mode was incorrect).  Listed output was "collapsed" this appears to be for the last test.

NVDA: 2024.4 Chrome :130

## Test Setup

- Test File: [test-65-activateLinkDropdown-nvda.collected.html](https://aria-at.netlify.app/tests/disclosure-navigation/test-65-activateLinkDropdown-nvda.collected.html)
- AT: NVDA (Version 2023.3)
- Browser: Chrome (Version 129)

## Review Conflicts for "Activate a link in a dropdown"

1.  ### Assertion Results for "Enter (browse mode on)" Command and "Role 'heading' is conveyed" Assertion
    
    *   Tester IsaDC recorded output " collapsed" and marked assertion as failing.
    *   Tester jha11y recorded output " Mythical University sample page content region Overview heading level 3 Sample content section. Activating a link above will update and navigate to this region." and marked assertion as passing.
2.  ### Assertion Results for "Enter (browse mode on)" Command and "Content of the heading, 'Overview', is conveyed" Assertion
    
    *   Tester IsaDC recorded output " collapsed" and marked assertion as failing.
    *   Tester jha11y recorded output " Mythical University sample page content region Overview heading level 3 Sample content section. Activating a link above will update and navigate to this region." and marked assertion as passing.
3.  ### Assertion Results for "Enter (browse mode on)" Command and "Role 'Region' is conveyed" Assertion
    
    *   Tester IsaDC recorded output " collapsed" and marked assertion as failing.
    *   Tester jha11y recorded output " Mythical University sample page content region Overview heading level 3 Sample content section. Activating a link above will update and navigate to this region." and marked assertion as passing.
4.  ### Assertion Results for "Enter (browse mode on)" Command and "Name of the region, 'Mythical University sample page content', is conveyed" Assertion
    
    *   Tester IsaDC recorded output " collapsed" and marked assertion as failing.
    *   Tester jha11y recorded output " Mythical University sample page content region Overview heading level 3 Sample content section. Activating a link above will update and navigate to this region." and marked assertion as passing.

**Comment by IsaDC** [comment]
Closing this issue as it has been resolved in the latest NVDA update.
