### ISSUE TITLE
VoiceOver bot providing incorrect output when testing Action Menu Button Example Using element.focus(), Test 1, V24.10.31)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#1160]
## Description of Behavior

The VoiceOver bot output was incorrect.  Two tests claimed no output but there was output.

## Test Setup

- Test File: [test-05-navForwardsToMenuButton-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/menu-button-actions/test-05-navForwardsToMenuButton-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (Version 13.7)
- Browser: Safari (Version 18)

**Comment by IsaDC** [comment]
The correct test output has been provided by human testers.
