### ISSUE TITLE
Who should review and merge things to master?

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-at#125]
We should decide who will review and merge changes to master. This will likely be different for different directories.

Also document this in the wiki.

**Comment by zcorpan** [comment]
> Matt_King: adding zcorpan as a person who can review and merge
> Matt_King: I think right now only spectranaut can merge to master

@michael-n-cooper can you give me authorization to merge to master? I can update documentation.

**Comment by michael-n-cooper** [comment]
Simon now has merge access to master of aria-at.

**Comment by zcorpan** [comment]
Now documented in https://github.com/w3c/aria-at/wiki/Working-Mode#github-management

Thanks!
