### ISSUE TITLE
Set up project board for test plans

### ISSUE THREAD

**Issue by mfairchild365** [w3c/aria-at#126]
One card for each test plan. Each column corresponds to a task in the working mode document

**Comment by mfairchild365** [comment]
@zcorpan Sounds like you are going to explore creating a script to create these issues. Let me know what I can do to help.

**Comment by zcorpan** [comment]
The cols could be:

* Backlog
* Prioritized
* Research stage & proposal (step 1-5)
* Internal review (step 6)
* External review (step 7-8)
* Ready to run / waiting for reviewed test results (step 10-15)
* Complete (step 16)

**Comment by mfairchild365** [comment]
Thank you @zcorpan - I made the columns a bit more granular since it may be valuable in quickly identifying what is holding up progress. I'm happy to revise as needed. Thoughts? https://github.com/w3c/aria-at/projects/1

**Comment by zcorpan** [comment]
@mfairchild365 there's an API to create project board cards

https://developer.github.com/v3/projects/cards/#create-a-project-card

I don't have bandwidth to write a script for this this week. I wouldn't mind if you gave it a try sooner if you have time. :)

**Comment by zcorpan** [comment]
The columns looks good to me!

**Comment by mfairchild365** [comment]
@zcorpan @mcking65 - is there an index of examples that I can reference to generate issues? If not, I can either create them manually or create a script that looks for links that have an `href` value that starts with `examples/`.

I assume that we want issues for each example and not just a project card?

**Comment by zcorpan** [comment]
https://w3c.github.io/aria-practices/examples/ has an index.

GitHub UI provides an easy way to create an issue from a project card.  ("Convert to issue" in the card's menu.) The issue list would be a bit shorter if we only create issues when we transition from backlog to the next stage.

**Comment by zcorpan** [comment]
That said, we probably want these issues to follow a standard template. I don't know if we can get that from "convert to issue". Creating all issues with the script and with the right template might be better.

**Comment by mfairchild365** [comment]
I have a script ready to go. I tested it by creating a single card. 

@mcking65 Before I generate all cards, should I hard code links to include an APG version?  https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/alertdialog.html vs https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/alertdialog.html

**Comment by mfairchild365** [comment]
I added cards to [the project board](https://github.com/w3c/aria-at/projects/1). @zcorpan can you take a quick look and make sure that everything looks right?

Script: 

```
/**
 * create .env file with the following:
 *   GITHUB_TOKEN=yourkey
 *   GITHUB_PROJECT_COLUMN_ID=yourcolumnid
 *
 * install the following packages with NPM
 * - @octokit/rest - github API
 * - puppeteer - a little heavy, but makes it easy to find all of the links
 * - dotenv - read the .env file with your secrets/config
 */

const { Octokit } = require("@octokit/rest");
const puppeteer = require('puppeteer');
const dotenv = require('dotenv');
dotenv.config();

const octokit = new Octokit({
	auth: process.env.GITHUB_TOKEN
});

const url = 'https://w3c.github.io/aria-practices/';

(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();

	// Navigate to the aria-practices page
	await page.goto(url);

	// Grab links to examples
	let examples = await page.evaluate(url => {
		let data = [];
		document.querySelectorAll('.widget a[href^="examples/"]').forEach(el => {
			console.log(el);
			let row = {};
			row.title = el.innerText.trim();
			row.url = url+el.getAttribute('href');
			data.push(row);
		});

		return data;
	}, url);

	await browser.close();

	var i = 0;
	examples.forEach(ex => {
		if (i > 0) {
			// This was just for testing purposes
			//return;
		}

		// Add the card
		octokit.projects.createCard({
			column_id: process.env.GITHUB_PROJECT_COLUMN_ID,
			note: "Test plan for ["+ex.title+"]("+ex.url+")"
		});

		i++;
	});
})();

```

**Comment by zcorpan** [comment]
Very nice! So now we have a bunch of cards. From there, you can convert a card to an issue. But we still need issue templates, similar to https://github.com/w3c/aria-at/issues/55 . See https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository (needs access to the settings pane, which I don't have) or https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository

**Comment by zcorpan** [comment]
PR for issue template: https://github.com/w3c/aria-at/pull/141

**Comment by zcorpan** [comment]
Hmm. The issue template isn't used when converting a card to an issue, as far as I can tell. I have contacted GitHub support with this message:

> See https://github.com/w3c/aria-at/issues/126#issuecomment-606626352
>
> We have a bunch of cards in a project board, with the plan to convert them to issues when we start to work on them. We created an issue template with the hope to be able to use it in this workflow. Unfortunately, it appears it is only possible to use issue templates from the normal "create new issue" flow, not when converting a card to an issue in a project board.

**Comment by mfairchild365** [comment]
@zcorpan - let me know what you find out. Some alternative approaches:

1. Whenever we convert a card to an issue, manually copy over the template. Cons: we might forget
2. Delete the existing cards and replace them with issues (and generate those issues). Cons: our issue tracker will explode

**Comment by zcorpan** [comment]
@mcking65 pointed out that we can create an issue normally from the template, and then link to it from the card.

I think that should work well enough, and we can close this.
