### ISSUE TITLE
Aria-AT Wireframes: Account Settings and Users Page

### ISSUE THREAD

**Issue by isaacdurazo** [w3c/aria-at#148]
# Account Settings
This page is accessible through the main menu by clicking the gear icon and selecting "Account settings" from the dropdown menu. There are two sections in this page 1) User details and 2) Assistive Technologies

## User Details
This section pulls the user's basic info from Github: email address and username. 

## Assistive Technologies
This section is a checkbox list of the Assistive Technologies that we have recorded in the system as available options for testers to perform tests with. Once the tester selects the ATs of their choice, a "save" button underneath the list is enabled. The tester can now save their selection and this will be recorded in the system.

![Account Settings](https://user-images.githubusercontent.com/1379244/78313935-3b694200-750d-11ea-8467-eada527920d5.png)

# Users
This page is accessible through the main menu by clicking the gear icon and selecting "Users" from the dropdown menu. It is only accessible for admins, there is only one table in this page and it is not editable. The table has the following columns:

  1. Username
  2. Email
  3. Role

![Users](https://user-images.githubusercontent.com/1379244/78313922-33110700-750d-11ea-9ec0-c0d58615ccbf.png)

**Comment by mcking65** [comment]
Isaac, Looking good. Just a few ideas/questions.

> # Account Settings
> This page is accessible through the main menu by clicking the gear icon and selecting "Account settings" from the dropdown menu. 

In #132, I wrote down some thoughts about global navigation across the app. Do we have a design for the main menu?

I am a little concerned about burying primary nav in a popup menu. Perhaps that is less of a concern if we have a home page that is directly accessible from the banner and has links to the main sections of the app. Something to discuss.

We should discuss the header and footer content that will be present on all pages of the app.

>There are two sections in this page 1) User details and 2) Assistive Technologies
> 
> ## User Details
> This section pulls the user's basic info from Github: email address and username.
Perhaps we show only the github username and make it a link to the github profile. Then, anyone who looks at this page can link to the profile on GitHub, and the user's GitHub profile controls how much info is revealed.

Although, if the user provided a real name on GitHub and made it public, then it would be nice to include their actual name.

> ## Assistive Technologies
> This section is a checkbox list of the Assistive Technologies that we have recorded in the system as available options for testers to perform tests with. Once the tester selects the ATs of their choice, a "save" button underneath the list is enabled. The tester can now save their selection and this will be recorded in the system.


Should we be displaying information about the github teams in which the user is a member? The tester team, the admin team?

> # Users
> This page is accessible through the main menu by clicking the gear icon and selecting "Users" from the dropdown menu. It is only accessible for admins,

Why does this have to be limited to admins. Perhaps anyone should be able to see it? Perhaps we hide the email from people who are not admins.

>there is only one table in this page and it is not editable. The table has the following columns:
> 
> 1. Username

Could this be a link to the github profile?

> 2. Email

Would be helpful if this is a mailto link.

> 3. Role

Could we have a column for "Tests Using" that lists the AT that a tester has included in their profile?

**Comment by isaacdurazo** [comment]
Thanks @mcking65 here my response to your comments:

>In #132, I wrote down some thoughts about global navigation across the app. Do we have a design for the main menu?

The Wireframes include a design for the navigation but I'm just realizing I did not include that in my descriptions. I will be adding that so you are able to review.

>Perhaps we show only the github username and make it a link to the github profile. Then, anyone who looks at this page can link to the profile on GitHub, and the user's GitHub profile controls how much info is revealed.

Making it a link sounds good.

>Although, if the user provided a real name on GitHub and made it public, then it would be nice to include their actual name.

Maybe we can have both, real name and username?

>Should we be displaying information about the github teams in which the user is a member? The tester team, the admin team?

Great idea. I'll make sure we add this info

>Why does this have to be limited to admins. Perhaps anyone should be able to see it? Perhaps we hide the email from people who are not admins.

Sounds good!

In addition to this. We'll make sure all usernames are links to the users's GitHub profile, emails are mailto's and we'll also add a Tests Using column this is info will be already recorded in the Account settings page.

**Comment by isaacdurazo** [comment]
Closing this discussion now. I will be creating new issues for new wireframe iterations
