### ISSUE TITLE
aria-at-harness.mjs shouldn't use sync XHR

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-at#161]
While looking at the `aria-at-harness.mjs` file I noticed that it uses *sync* XHR, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#Synchronous_request) (because it blocks the main thread).

This should be replaced with `fetch()`.

**Comment by alflennik** [comment]
I'll take stab at this! Thanks for keeping a great list of newbie issue like this.

**Comment by alflennik** [comment]
mfairchild fixed this on May 22, 2020 in [this commit](https://github.com/w3c/aria-at/commit/0a88a6ceae079db866c561fbac26576519cca2f9#diff-d6433a05959d2cc5167305cf343e1fe3a4f924e76f44f7ae620348474d7a8694).

Even if I didn't get code in yet, that was fun 😊 and I learned a lot bouncing around the code.

We can close it @zcorpan !
