### ISSUE TITLE
Use linear git history

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-at#164]
See https://www.bitsnbites.eu/a-tidy-linear-git-history/ -- I think there are advantages to a linear git history. In particular, when reviewing what has happened in the past, a clean linear history is much easier to work with. Right now there are a few merge commits in master.

It GitHub, this can be enforced by:

* Uncheck "Allow merge commits" under [Options, Merge button](https://github.com/w3c/aria-at/settings#merge-button-settings).
* Check "Require linear history" for `master` under [Branches](https://github.com/w3c/aria-at/settings/branches).

In PRs, the merge button would only allow "squash and merge" (a single commit) or "rebase and merge" (if you want to preserve multiple commits).

@mfairchild365 thoughts? @michael-n-cooper can you change this in the settings?

**Comment by mfairchild365** [comment]
@zcorpan I think that's a good plan.

**Comment by michael-n-cooper** [comment]
I checked with other ARIA editors to see if there were concerns. They were ok for you to do this for the aria-at repo, so I've implemented, thanks for the clear instructions.

**Comment by zcorpan** [comment]
Excellent, thank you!
