### ISSUE TITLE
Regression from #171: uncaught exception

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-at#175]
From #171 this line now throws an exception
```js
    let commandsData = this.AT_COMMAND_MAP[task][mode][assistiveTech.key] || [];
```
```
Uncaught (in promise) TypeError: Cannot read property 'key' of undefined
    at commandsAPI.getATCommands (at-commands.mjs:62)
    at verifyATBehavior (aria-at-harness.mjs:143)
    at test-01-navigate-to-unchecked-checkbox-reading.html:20
```

cc @mfairchild365 @spectranaut

**Comment by zcorpan** [comment]
Made a PR to revert, if unbreaking it urgent https://github.com/w3c/aria-at/pull/176

**Comment by spectranaut** [comment]
I couldn't replicate this bug, although I found another one soon to come!

**Comment by zcorpan** [comment]
Sorry, false alarm. This happened because of another bug in the prototype runner, where `index.html` files show up as tests that can be run.
