### ISSUE TITLE
index.html links does not work 

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#180]
I am working updating the menubar-editor tests and I did a merge from master.
When I try to check the updated tests using the pages referenced in the `index.html` file in the `menubar-editor` directory the links reference broken test pages.  It seems the error in  generating a test page is related to specifying an Assistive Technology.  Not sure where this should be in the script.

**Comment by mfairchild365** [comment]
@jongund thanks for reporting this. I made a PR. Feel free to [manually implement the fix](https://github.com/w3c/aria-at/pull/181/files) until it is merged so that you are not blocked.

**Comment by jongund** [comment]
@mfairchild365 

I have modified the creation script in [Branch menubar-assertion-updates](https://github.com/w3c/aria-at/tree/menubar-assertion-updates) to generate URLs for each of the ATs a test supports, that will help with development of the test cases and reviewing what ATs a test case applies to.

Here is a [preview of the updated index page](https://raw.githack.com/w3c/aria-at/menubar-assertion-updates/tests/menubar-editor/index.html)
