### ISSUE TITLE
Tester issue report for: "Navigate into a checkbox group in reading mode"

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#205]
#### Test file at exact commit

[tests/checkbox/test-21-navigate-into-checkbox-group-reading.html](https://github.com/w3c/aria-at/blob/2a3c46f1cbd20e7f2f0a706052d2d82aaf207a29/tests/checkbox/test-21-navigate-into-checkbox-group-reading.html)

#### Cycle:

Test Pilot (2020-05-27)

#### AT:

NVDA (version 2020.1)

#### Browser:

Chrome (version 83.0.4103.61)

#### Description

There are separate cases for F and Shift+F, but the latter of these incorrectly includes both F and Shift+F in its description.  As such, the two cases are "F" and "F/Shift+F".

**Comment by mfairchild365** [comment]
Thank you, @jscholes for reporting this. Feedback like this is very helpful. We will fix it after the pilot so that we don't change tests mid-cycle.

**Comment by spectranaut** [comment]
We can actually fix it whenever, it won't affect the test cycle! :) The test cycle is testing the aria-at tests at a specific revision, so any future commits won't effect the Pilot Test test cycle.

**Comment by mfairchild365** [comment]
Oh! That's awesome. So we can fix it, but it won't reflect in the pilot test cycle. Correct?

**Comment by zcorpan** [comment]
Correct. When initiating a test cycle, you can choose which commit of `aria-at` to use, and that won't change for that test cycle.

**Comment by mcking65** [comment]
Line 28 of resources/keys.mjs isincorrectly:
```
export const SHIFT_F                          = "F / Shift+F";
```
