### ISSUE TITLE
Tester issue report for: "Navigate to menubar"

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#206]
### Test file at exact commit

[tests/menubar-editor/test-05-navigate-to-menubar-interaction.html](https://github.com/w3c/aria-at/blob/2a3c46f1cbd20e7f2f0a706052d2d82aaf207a29/tests/menubar-editor/test-05-navigate-to-menubar-interaction.html)

### Cycle:

Test Pilot (2020-05-27)

### AT:

VoiceOver for macOS (version macOs 10.15.4)

### Browser:

Safari (version 13.1)

### Description

The control + option + right arrow does not allow navigation to menubar, need to go up a level in the tree and then navigate to the editor region and then use additional navigation commands to find the menubar items.

**Comment by mfairchild365** [comment]
Thank you for the report, @jongund. I could not replicate the issue [when testing in the prototype runner](https://w3c.github.io/aria-at/tests/menubar-editor/test-05-navigate-to-menubar-interaction.html?at=voiceover_macos).

I could, however, replicate the issue after going to the VoiceOver Utility's web settings and changing "navigate webpages by" to "Grouping items". The default setting is "DOM order". Can you confirm that this setting is set to "DOM order"? If it is not, please try changing it to "DOM order" and try the test again.

**Comment by jongund** [comment]
The grouping option was set so I reset my voice over configuration and will redo the test.

Jon
