### ISSUE TITLE
Feedback on test: Pausing testing until I get answers to other feedback

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-at#261]
Rather than continue to pollute the issue tracker with repetitive feedback and doing a bunch of work that is eventually scrapped because I've misinterpreted the intent/procedure of the tests, I'm going to pause my testing until I get some responses or until we've had a chance to talk about things in our next meeting, whichever comes first.  On the bright side, I've got all the checkbox tests I was signed up for done and a number of the tests for the menubar and provided a lot of feedback (probably too much).  Just let me know how you'd like me to proceed and I'll be glad to pick things back up again as best I'm able.

**Comment by robfentress** [comment]
I was sick today (Tuesday) and so was unable to finish the rest of the menubar tests after receiving responses to some of the issues I'd raised yesterday.  Although I still tried to do some more later in the evening when I was feeling a little better, it is 10:32 now and I've gotta get to sleep.  Sorry I wasn't able to finish everything by the end of the day.

**Comment by zcorpan** [comment]
Thank you @robfentress . I've added Agenda+

**Comment by zcorpan** [comment]
I was going to close this since we're past the pilot test end date. But I think we can keep this open for now, and discuss how to be more responsive to issues from testers in future test cycles.

**Comment by mcking65** [comment]
Overcome by events
