### ISSUE TITLE
Feedback on test: "open test cycle" is not loading.

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-at#269]
ARIA-AT Testing URL is not loading, https://aria-at.w3.org/test-queue/2 and it only shows gray background color. I have looked at error console and I see this message.
 
Problem url: https://aria-at.w3.org/test-queue/2
 
action     {type: "TESTS_BY_RUN_ID", payload: {…}}
error      TypeError: Output is excessively verbose, e.g., includes redundant and/or irrelevant speech is not a function

Thanks for checking.

**Comment by mfairchild365** [comment]
Thank you for reporting this, @a11ydoer - I do not see that error when visiting that URL. Can you try again? Perhaps there was an outage over the weekend.

**Comment by a11ydoer** [comment]
@mfairchild365 I am still having the problem. Can you flush out my test data for NVDA and Chrome so that I can do testing? The error I had was attributed from choosing the option of "Output is excessively verbose"

**Comment by mfairchild365** [comment]
@a11ydoer unfortunately, I can't delete results. The button to do so is disabled.

@zcorpan do you have any insight into this issue?

**Comment by zcorpan** [comment]
Thanks! @spectranaut fixed this yesterday. @a11ydoer can you try again?

The error message is pretty confusing. The problem was "A string was provided, expected a function" for `Array.prototype.find`.

**Comment by a11ydoer** [comment]
@zcorpan @spectranaut Thanks for fixing this. It is working. Out of curiosity, I  as former developer, wonder why it happened only to me although I know the cause of the problem - I chose the option for  "Output is excessively verbose,"
