### ISSUE TITLE
Should we set a new meeting time?

### ISSUE THREAD

**Issue by mfairchild365** [w3c/aria-at#292]
Question from Matt King

**Comment by robfentress** [comment]
Do you mean a different time than Wednesdays at 3 PM EST?

**Comment by mcking65** [comment]
Yap, hoping to find a workable slot on Tuesday or Thursday. I'm striving to create more meeting-free blocks of time so I don't implode.

**Comment by mfairchild365** [comment]
From ARIA-AT call: we will be meeting every two weeks on Thursdays at 12pm PT, starting Sept 10th.
