### ISSUE TITLE
A way to see support for ARIA attributes at a glance

### ISSUE THREAD

**Issue by jfhector** [w3c/aria-at#3]
I'm opening this issue just so that we have a place to share some design research.

If you find useful references for how similar features are designed or implemented somewhere else, please share these examples here. Even when there are fundamental differences in the projects', having a wide range of examples and references will help us a lot when we think about design.

This for example is how the UK Government Digital Service uses Github issues to share useful design references for different features. https://github.com/alphagov/govuk-design-system-backlog/issues/133

**Comment by jfhector** [comment]
This is how Vispero documents supports for ARIA
https://freedomscientific.github.io/VFO-standards-support/aria.html

<img width="1422" alt="Screenshot 2019-04-24 at 20 15 33" src="https://user-images.githubusercontent.com/30028540/56687368-02560a00-66ce-11e9-9856-bcb7ef54b5b1.png">

Each row has a link to a test case page. Here's an example test case page, which happens to be covering several tests. http://stevefaulkner.github.io/HTML5accessibility/tests/ARIA-tests/#treegrid

<img width="1422" alt="Screenshot 2019-04-24 at 20 17 25" src="https://user-images.githubusercontent.com/30028540/56687407-14d04380-66ce-11e9-8ad9-6cceefdc6cd0.png">

**Comment by jfhector** [comment]
Other useful reference:
https://www.html5accessibility.com/

Table showing support different HTML 5 attributes, grouped by themes:
<img width="1263" alt="Table showing support different HTML 5 attributes, grouped by themes" src="https://user-images.githubusercontent.com/30028540/56989631-d41f7100-6b8a-11e9-88db-41bd317a44a1.png">

Table rows can be expanded to show more detailed test results:
<img width="1329" alt="Table rows can be expanded to show more detailed test results" src="https://user-images.githubusercontent.com/30028540/56989630-d41f7100-6b8a-11e9-99d6-d66fd3510431.png">

**Comment by mfairchild365** [comment]
@jfhector thank you for starting this issue and sharing those resources. I did some similar research when I started the a11ysupport.io project. A short summary of my findings are below:

* [Can I use](https://caniuse.com/) - This is very similar in concept, but only aims to answer the question "can I use feature x with browser y". It does not include assistive technology support. Developers can contribute data to it via GitHub.
* [PowerMapper Tests](https://www.powermapper.com/tests/screen-readers/) - This serves to answer the same question as this project, but is not open for contributions (as far as I can tell). Also has limited AT/browser combinations.
* [WAI ARIA 1.1 Tests](https://w3c.github.io/test-results/wai-aria/) - automated tests that are ran by the w3c. Focuses on ARIA 1.1 support between given browsers and accessibility APIs. Does not include support for specific ATs, which may not implement parts of the accessibility APIs correctly. Only focuses on ARIA 1.1. Has good test cases (example HTML) that we might be able to re-use. Does not appear to include all browsers (Internet Explorer, Chrome on Android, etc)
* [HTML5 Accessibility](https://www.html5accessibility.com/) - Tests HTML5 elements across several mainstream browsers. Only checks support at the browser, NOT the final AT. Only focuses on html5 elements, not ARIA, CSS, etc
* [VFO Standards support](https://freedomscientific.github.io/VFO-standards-support/html.html) - Very similar, but this only focuses on JAWS

**Comment by mfairchild365** [comment]
Also, see the [W3C WAI Accessibility Support Database](https://www.w3.org/WAI/accessibility-support/). This was a prototype project from a few years ago.  @spectranaut - you might find this interesting and it might also be worthwhile to investigate as an open-source project for #8.

**Comment by spectranaut** [comment]
Wow @mfairchild365 thanks for drawing my attention to this. I'm surprised we haven't talked about this, its so similar to what we are discussing to be build. 

@mcking65, what do you think of this project? The [W3C WAI Accessibility Support Database](https://www.w3.org/WAI/accessibility-support/) -- it is only a prototype, built back in 2014. The log in option does not seem to work with my w3c credentials.

**Comment by jnurthen** [comment]
@nitedog would know more about the https://www.w3.org/WAI/accessibility-support/ prototype.

**Comment by nitedog** [comment]
What would you like to know @jnurthen? This prototype tool was an attempt back in ~2010-2014 and is currently not actively supported for various reasons. All source code is freely available and we would be happy for it to be reused by the community. The log-in issue is probably due to changes in the internal LDAP configuration. We can revisit re-activating this or another tool in place of this tool if we can come up with a plan for maintenance and moderation. I would be delighted to help with such discussion and explore potential options.

**Comment by mfairchild365** [comment]
@jnurthen @nitedog Thank you for the details on this. We will reach out to you if we decide to investigate the tool further.

@spectranaut From today's call: we plan to stay focused on the CSS WG tool that we are currently investigating. We can review the W3C WAI Accessibility Support Database once we are done investigating the CSS WG tool (if needed).

**Comment by jscholes** [comment]
@mfairchild365 Can this be closed?  It seems to relate to:

1. tooling, for which discussions are now much further along; and
2. documenting of results, which seems to be covered in a more up-to-date fashion e.g. in https://github.com/w3c/aria-at-app/issues/241 and related discussions.

**Comment by mfairchild365** [comment]
Yes, I'll close this. I think it's still important and not fully resolved, but it's probably better to discuss it elsewhere and not really relevant to this repo anymore.
