### ISSUE TITLE
Create tests for APG design pattern example: Disclosure (Show/Hide) of Answers to Frequently Asked Questions

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#344]
#### Applies To

* APG design pattern: [Disclosure (Show/Hide)](https://w3c.github.io/aria-practices/#disclosure)
* Specific example: [Disclosure (Show/Hide) of Answers to Frequently Asked Questions](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-faq.html)

#### Testing Notes

This issue thread will house all documentation relating to the development of a test plan for the "Disclosure (Show/Hide) of Answers to Frequently Asked Questions" APG example, which conforms to the "Disclosure" design pattern.  All follow-ups (including the test plan itself) will be added as new comments to facilitate notifications, but this initial comment will be updated with relevant details and URLs as needed for convenience.

#### Useful Links

* [Previewable Tests Index](https://raw.githack.com/w3c/aria-at/tests/disclosure-faq/tests/disclosure-faq/index.html)
* [Previewable Tests Review Page](https://raw.githack.com/w3c/aria-at/tests/disclosure-faq/review/disclosure-faq.html)

#### Additional References

* [button (role)](https://w3c.github.io/aria/#button)
* [aria-expanded (state)](https://w3c.github.io/aria/#aria-expanded)

**Comment by IsaDC** [comment]
Below is the test plan for the Disclosure (Show/Hide) of Answers to Frequently Asked Questions example.  Each test title is marked up as a level 4 heading to facilitate screen reader navigation.

#### Navigate forwards to a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the collapsed state.
* Commands:
    * B
    * F
    * Tab
    * Down Arrow
* Setup script description: sets focus on a link before the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate backwards to a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the collapsed state.
* Commands:
    * Shift+B
    * Shift+F
    * Shift+Tab
    * Up Arrow
* Setup script description: sets focus on a link after the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the collapsed state.
* Commands:
    * Tab
* Setup script description: sets focus on a link before the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate backwards to a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the collapsed state.
* Commands:
    * Shift+Tab
* Setup script description: sets focus on a link after the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the collapsed state.
* Commands:
    * Tab
    * Control+Option+Right Arrow
* Setup script description: sets focus on a link before the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate backwards to a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the collapsed state.
* Commands:
    * Shift+Tab
    * Control+Option+Left Arrow
* Setup script description: sets focus on a link after the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the expanded state.
* Commands:
    * B
    * F
    * Tab
    * Down Arrow
* Setup script description: sets focus on a link before the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate backwards to an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the expanded state.
* Commands:
    * Shift+B
    * Shift+F
    * Shift+Tab
    * Up Arrow
* Setup script description: sets focus on a link after the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate forwards to an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the expanded state.
* Commands:
    * Tab
* Setup script description: sets focus on a link before the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate backwards to an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the expanded state.
* Commands:
    * Shift+Tab
* Setup script description: sets focus on a link after the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate forwards to an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the expanded state.
* Commands:
    * Tab
    * Control+Option+Right Arrow
* Setup script description: sets focus on a link before the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate backwards to an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the list of frequently asked questions. Note: it should be in the expanded state.
* Commands:
    * Shift+Tab
    * Control+Option+Left Arrow
* Setup script description: sets focus on a link after the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Read information about a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the list of frequently asked questions, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Read information about a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Read information about a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, read information about the button.
* Commands:
    * Control+Option+F3
    * Control+Option+F4
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Read information about an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the list of frequently asked questions, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Read information about an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Read information about an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, read information about the button.
* Commands:
    * Control+Option+F3
    * Control+Option+F4
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name, 'What do I do if I have a permit for an assigned lot, but can't find a space there?', is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the list of frequently asked questions, set the state of the button to expanded.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, set the state of the button to expanded.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, set the state of the button to expanded.
* Commands:
    * Control+Option+Space
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the list of frequently asked questions, set the state of the button to collapsed.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to collapsed) is conveyed|required|`aria-expanded="false"`|

#### Operate an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, set the state of the button to collapsed.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to collapsed) is conveyed|required|`aria-expanded="false"`|

#### Operate an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, set the state of the button to collapsed.
* Commands:
    * Control+Option+Space
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate from an expanded disclosure button to the text of a question answer in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the list of frequently asked questions, move into the text of the associated question answer. Note: you may need to press Down Arrow multiple times to hear the answer text in its entirety.
* Commands:
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Text of the answer is conveyed: 'Park at the nearest available parking meter without paying the meter and call 999-999-9999 to report the problem. We will note and approve your alternate location and will investigate the cause of the shortage in your assigned facility.'|required|Visible text content contained within the` <p>` element with `id="faq1_desc"`|

#### Navigate from an expanded disclosure button to the text of a question answer

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the list of frequently asked questions, move into the text of the associated question answer. Note: you may need to press Control+Option+Right multiple times to hear the answer text in its entirety.
* Commands:
    * Control+Option+Right Arrow
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded.

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Text of the answer is conveyed: 'Park at the nearest available parking meter without paying the meter and call 999-999-9999 to report the problem. We will note and approve your alternate location and will investigate the cause of the shortage in your assigned facility.'|required|Visible text content contained within the` <p>` element with `id="faq1_desc"`|

**Comment by jscholes** [comment]
These tests are ready for review. For convenience, I've added links to the previewable index and review pages in the initial comment.

* [Previewable Tests Index](https://raw.githack.com/w3c/aria-at/tests/disclosure-faq/tests/disclosure-faq/index.html)
* [Previewable Tests Review Page](https://raw.githack.com/w3c/aria-at/tests/disclosure-faq/review/disclosure-faq.html)
