### ISSUE TITLE
Should the screen reader setting to automatically read web pages on load be disabled for testing?

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#370]
In both JAWS and NVDA, the default settings cause web pages to automatically start reading when loaded.  Is there a possibility that this will interfere with the intended focus point implied by a setup script?  Is this irrelevant if setup scripts will only be executed by the press of a button, as users will need to interrupt an automatic say-all to find the button?

**Comment by mcking65** [comment]
I think this is another reason to have the user run setup script manually after page load. It lets us keep the screen reader running with default settings.

**Comment by jscholes** [comment]
@mcking65 Agree completely.

**Comment by jscholes** [comment]
Adding the test-runner label, as changes will be needed to allow testers to manually execute setup scripts.

**Comment by jscholes** [comment]
Closing this; the test runner will facilitate a button to execute setup scripts after page load so this will no longer be an issue.
