### ISSUE TITLE
Create tests for APG design pattern: Button Examples

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-at#373]
APG design pattern: https://w3c.github.io/aria-practices/examples/button/button.html

- [ ] Test committed:
- Test reviewed:
   - [ ] Review of test description
   - [ ] JAWS commands
   - [ ] NVDA commands
   - [ ] VoiceOver commands
- [Test results](https://w3c.github.io/aria-at/results/)
  - [ ] JAWS/Chrome
  - [ ] JAWS/Firefox
  - [ ] NVDA/Chrome
  - [ ] NVDA/Firefox
  - [ ] Mac VoiceOver/Chrome
  - [ ] Mac VoiceOver/Safari

**Comment by robfentress** [comment]
I was working off of the [How to contribute tests](https://github.com/w3c/aria-at/wiki/How-to-contribute-tests) wiki page to create the tests for the button pattern, but skipped over the description of the [process in the working mode document](https://github.com/w3c/aria-at/wiki/Working-Mode#process).  I fear I may have jumped the gun here, skipping straight to the Internal Review step in the Test Plan Workflow.  I have already pushed the [branch for the button pattern](/w3c/aria-at/tree/tests/button).  Should I go backwards and try to follow the something like the general pattern I'm seeing in #348 or would that be wasted effort and it would be better to just submit a pull request for my branch?  Since button was so similar to the checkbox example, most of what I had to do just involved paring down and tweaking of the commands, tests, and assertions listed there.  

I'm sorry if I've fubbed this up, but I was concentrating so much on figuring out the technical aspect of how things worked in the limited time I had over break that I seem to have paid insufficient attention to the actual process.

**Comment by robfentress** [comment]
I also noticed that running create-all-tests updated the root directory referenced on the index pages of all the tests to reference my local directory structure.  I went ahead and committed that, but it seems like it could be misleading for others, and I don't particularly like the fact that I am sharing that info with the world.  Did I do something wrong there?

**Comment by robfentress** [comment]
Also, I ran the [update-reference script](https://github.com/w3c/aria-at/blob/master/scripts/update-reference.js) to pull the [example from the aria-practices repo](https://github.com/w3c/aria-practices/tree/master/examples/button), but I didn't know if I was supposed to manually edit the example page so that it only included the actual example and not the info _about_ the example.  I left it as is, but if I'm supposed to edit it, is there specific guidance on the way you'd like folks to do that?

**Comment by jscholes** [comment]
@robfentress

> I have already pushed the branch for the button pattern. Should I go backwards and try to follow the something like the general pattern I'm seeing in #348 or would that be wasted effort and it would be better to just submit a pull request for my branch?

Myself, @IsaDC and @sinabahram have been following a pattern of our own design, at least in terms of issue body templates and human-readable test plans.  It is my aim in the new year to raise a discussion about how much of that pattern should be documented project-wide, to increase consistency with everybody following a similar workflow and structure.

In other words, right now it's entirely up to you to determine whether you have the time to follow it or not.  Putting the human-readable plans together in Markdown is not a small job and there isn't an existing one for checkbox to work from.  You should submit a PR regardless, though, to allow the community group to review your contributions, and I think the initial comment in this issue should ideally follow the template we've been using.

> I also noticed that running create-all-tests updated the root directory referenced on the index pages of all the tests to reference my local directory structure.

You don't need to run this locally.  There's a GitHub Action to do it server-side, so running it on your own machine is only really useful for testing.

> if I'm supposed to edit it [the example], is there specific guidance on the way you'd like folks to do that?

I don't believe there is any documentation, other than what the update reference script prints at the end.  The best thing to do would be to take a look at the branches already submitted, both in terms of the edits made to the HTML and the commits which explain those edits.  For example: https://github.com/w3c/aria-at/commits/tests/checkbox-tri-state

**Comment by jscholes** [comment]
Oh, I should note: the GitHub Action runs when you push to a branch associated with a PR, so that's another reason to submit one.

**Comment by jscholes** [comment]
Closing this in favour of #395 and #396, which will separate the tests into two separate plans for the command and toggle buttons.  See https://github.com/w3c/aria-practices/issues/1795 for more info.
