### ISSUE TITLE
Proposed Patterns for Test Plan Development (Q1/Q2 2021)

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#385]
Issue #318 outlines the initial 13 patterns to be worked on by members of the PAC team.  We are approaching the completion point on those patterns (status outlined below), and want to take input from the community group on which patterns to tackle next.

#### Current Status

* Pull requests have been submitted for 8 of the 13 patterns.
* Test plans for two patterns have been prepared but are undergoing internal PAC review: Tabs With Manual Activation and Minimal Data Grid.
* The test plans for two patterns are currently being written: Radio Group Using Roving tabindex and Radio Group Using aria-activedescendant.
* One pattern has been intentionally skipped for now: Date Picker Combobox.  It's thought that this could benefit from a more compositional approach to test development.

**Comment by jscholes** [comment]
Update from Feburary 4th community group meeting: over the next weeks, we want to focus on preparing tests for roles which haven't yet been touched.  Specifically:

* slider;
* tree;
* spinbutton;
* toolbar; and
* feed (further discussion most likely required).

Specific examples of the above patterns will be proposed as a further comment on this issue.

**Comment by jscholes** [comment]
Proposed next patterns:

1. [File Directory Treeview Example Using Computed Properties](https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html)
2. [File Directory Treeview Example Using Declared Properties](https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html)
3. [Date Picker Spin Button Example](https://w3c.github.io/aria-practices/examples/spinbutton/datepicker-spinbuttons.html)
4. [Toolbar Example](https://w3c.github.io/aria-practices/examples/toolbar/toolbar.html)
5. [Horizontal Slider Examples](https://w3c.github.io/aria-practices/examples/slider/slider-1.html)
6. [Slider Examples with aria-orientation and aria-valuetext](https://w3c.github.io/aria-practices/examples/slider/slider-2.html)

**Comment by IsaDC** [comment]
Final prioritized list:

1. [Navigation Treeview Example](https://w3c.github.io/aria-practices/examples/treeview/treeview-navigation.html)
2. [Button Examples](https://w3c.github.io/aria-practices/examples/button/button.html)
3. [Toggle Button](https://w3c.github.io/aria-practices/examples/button/button.html)
4. [Date Picker Spin Button Example](https://w3c.github.io/aria-practices/examples/spinbutton/datepicker-spinbuttons.html)
5. [Toolbar Example](https://w3c.github.io/aria-practices/examples/toolbar/toolbar.html)
6. [Horizontal Slider Examples](https://w3c.github.io/aria-practices/examples/slider/slider-1.html)
7. [Slider Examples with aria-orientation and aria-valuetext](https://w3c.github.io/aria-practices/examples/slider/slider-2.html)
8. [File Directory Treeview Example Using Declared Properties](https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html)

**Comment by jscholes** [comment]
Notes from March 25, 2021 meeting:

* Add multithumb slider to the list (will be merged soon).
* Revisit toolbar during a future meeting to determine:
    * the scope of APG toolbar tests; and
    * best process for bringing non-APG HTML in for testing.

**Comment by mcking65** [comment]
completed work
