### ISSUE TITLE
Do we need multiple agenda labels to match the meeting plan?

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#386]
We have two agenda-related labels at present: "Agenda+" and "Agenda+ F2F", the latter of which seems somewhat irrelevant for this project particularly in the current climate.  Therefore, anything to be discussed during an online meeting falls into the "Agenda+" bucket; we currently have 26 open issues with that label, the oldest of which is from November 2019.

To allow meeting agendas to be more efficiently organised, would it be a good idea to create separate agenda labels for the distinct meeting types outlined on the [2021 meeting plan](https://github.com/w3c/aria-at/wiki/Meetings)?  Specifically:

* community group meetings focused on screen reader test writing and manual test runs;
* community group meeting focused on a round up of work across all workstreams (last week of month);
* ARIA-AT app Development meetings focused on design and engineering of the aria-at.w3.org app; and
* assistive technology automation development meetings focused on development of the assistive technology automation driver for running ARIA-AT tests.

Note that we do already have labels for specific areas like automation, the test runner, etc.  But these aren't directly used for agendas, and it's feasible that an issue will be filed which relates to one of those areas but doesn't need on-call discussion, or that an issue remains open after it's been discussed for further async comments.

**Comment by jscholes** [comment]
Proposal from Feburary 4th community group meeting:

* Rename current "Agenda+" label to "Agenda+Community Group", which will apply to the last CG call in each month.
* Create three new labels: "Agenda+Test Writing", "Agenda+Automation" and "Agenda+App Development", with appropriate descriptions, to match the 2021 meeting plan.
* Begin moving existing issues with "Agenda+Community Group" label into appropriate labelled buckets.

**Comment by jscholes** [comment]
@s3ththompson I've made the proposed changes, but haven't yet started moving issues into buckets.

**Comment by mcking65** [comment]
done
