### ISSUE TITLE
Create updated tests for APG design pattern example: Command Button

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#395]
#### Applies To

* APG design pattern: [Button](https://w3c.github.io/aria-practices/#button)
* Specific example: [Button Examples](https://w3c.github.io/aria-practices/examples/button/button.html); only the "command button" labelled "Print Page"

#### Testing Notes

This issue thread will house all documentation relating to the development of a test plan for the "Button" APG example, which conforms to the "Button" design pattern.  All follow-ups (including the test plan itself) will be added as new comments to facilitate notifications, but this initial comment will be updated with relevant details and URLs as needed for convenience.

#### Additional References

* [button (role)](https://w3c.github.io/aria/#button)

**Comment by jscholes** [comment]
Below is the test plan for the button example.  Each test title is marked up as a level 4 heading to facilitate screen reader navigation.

#### Navigate forwards to a button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Mode: reading, interaction
* Instructions:
    * Reading mode: with the reading cursor on the 'Navigate forwards from here' link, navigate to the 'Print Page' button.
    * Interaction mode: With focus on the 'Navigate forwards from here' link, navigate to the 'Print Page' button.
* Setup script description: Sets focus on a link before the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading|<ul><li>Down Arrow</li><li>B</li><li>F</li><li>Tab</li></ul>|
|JAWS, NVDA|interaction|Tab|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Right Arrow</li><li>Tab</li><li>Control+Option+Command+J</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Print Page' is conveyed|required|

##### References

`button`

#### Navigate backwards to a button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Mode: reading, interaction
* Instructions:
    * Reading mode: with the reading cursor on the 'Navigate backwards from here' link, navigate to the 'Print Page' button.
    * Interaction mode: With focus on the 'Navigate backwards from here' link, navigate to the 'Print Page' button.
* Setup script description: Sets focus on a link after the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|reading|<ul><li>Up Arrow</li><li>Shift+B</li><li>Shift+F</li><li>Shift+Tab</li></ul>|
|JAWS, NVDA|interaction|Shift+Tab|
|macOS VoiceOver|interaction|<ul><li>Control+Option+Left Arrow</li><li>Shift+Tab</li><li>Shift+Control+Option+Command+J</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Print Page' is conveyed|required|

##### References

`button`

#### Read information about a button

* Applies to: JAWS, NVDA, macOS VoiceOver
* Mode: reading, interaction
* Instructions:
    * Reading mode: with the reading cursor on the 'Print Page' button, read information about the button.
    * Interaction mode: With focus on the 'Print Page' button, read information about the button.
* Setup script description: Sets focus on the button

##### Commands

|AT|Mode|Commands|
|---------|--------|-----|
|JAWS, NVDA|<ul><li>reading</li><li>interaction</li></ul>|<ul><li>Insert+Tab</li><li>Insert+Up</li></ul>|
|macOS VoiceOver|interaction|<ul><li>Control+Option+F3</li><li>Control+option+F4</li></ul>|

##### Assertions

|Assertion|Priority|
|---------|--------|
|Role 'button' is conveyed|required|
|Name 'Print Page' is conveyed|required|

##### References

`button`
