### ISSUE TITLE
Improvements to high-level use cases wiki page

### ISSUE THREAD

**Issue by jfhector** [w3c/aria-at#4]
I’ve created a [wiki page called 'High level use cases'](https://github.com/w3c/aria-at/wiki/High-level-use-cases). 

I'm opening this issue as a place to discuss modifications to that wiki page.

**Comment by mfairchild365** [comment]
Thank you for putting this together, @jfhector 

One quick question: under 1.1, there is this outcome:

> As many users as possible find the interface easy to use.

Does "the interface" refer to the interface the web developer is building, or the interface for the data that we are providing?

**Comment by jfhector** [comment]
Thanks @mfairchild365 for spotting this ambiguity.

I've just fixed the phrasing under 1.1 and 1.2 to say:
> As many users as possible find the interface I'm developing easy to use.

Spelling out our users' / stakeholders' situations of struggles and desired outcomes is a way to better understand their needs.

So the 'Outcomes they're hoping for' are _their_ desired outcomes as they experience the situation of struggle – rather than ours.

**Comment by jfhector** [comment]
Here's a diagram with an example of how understanding someone's 'situation of struggle' and 'desired outcomes' helps us understand their needs. (I've put it together for a design conference last week).

![Method diagram described below](https://user-images.githubusercontent.com/30028540/59608361-16861880-910d-11e9-9d7a-431d3638e654.jpg)

The diagram represents someone who's experiencing a situation of struggle. It's the morning and they are leaving home for the day. They're in a rush. They don’t know what clothes, jacket or other rain equipment they might need during the day. This is a situation of struggle.

The outcomes they're hoping for is that they enjoy their day and stay dry, and that they're out of the door immediately so as not to be late.

Experiencing this situation of struggle is a bit like being stuck on one side of a river, not knowing how to get to the other side. The other side of the river represents the outcomes that the person is hoping for.

In this example, that person thinks of different ways to go from their situation of struggle to their desired outcomes. They could look at a weather app, they might just look at the sky, or they might just take a chance and just guess what sort of clothes or rain equipment they'll need. Different solutions have different pros and cons.

Starting from our users' situations of struggle and desired outcomes (rather than feature ideas) is a useful way to make sure that we design things that are actually helpful to them. It helps us compare our design ideas with other solutions our users already have available to our users, and avoid waste.

**Comment by spectranaut** [comment]
Closed because this document is complete.
