### ISSUE TITLE
Test review coordination

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#410]
Just providing a placeholder/kickoff issue for an item on the next CG meeting agenda (April 1).  Need to discuss how test reviews will be coordinated once test plans are merged, how to find/reach out to volunteers, etc.

**Comment by jscholes** [comment]
Updates from April 1, 2021 CG meeting:

* We don't yet have a wiki page declaring the standards, practices, patterns, etc. used by test writers, to allow reviewers to compare the content of test plans against what is expected (#419).
* If people are to use the test runner to execute tests and review them in-place, there are certain steps they need to carry out: creating a GitHub account, joining a specific GitHub org/group to get access to the test runner, etc.  These steps currently aren't documented/defined and we need a "Getting Started" page to help us all out (#420).
* A vocabulary/glossary page would be helpful, separate from the Working Mode (#421).

**Comment by mcking65** [comment]
addressed by referenced issues above
