### ISSUE TITLE
Test content wording (incl. assertions)

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#413]
On a recent community group meeting, @mcking65 mentioned that he thinks the wording used within tests (and maybe the test runner?) can be cleaned up/made clearer, a goal which I think we can all agree with.  I'm creating this issue both to act as a placeholder for follow-up discussion on that point, and as an input to the upcoming deep dive on changes to the test format.

The latter is an important crossover, because one of the objectives within the test format is to reduce duplication, abstract out commonly used aspects, etc.  For instance, the majority of tests include a role-related assertion and there are opportunities to standardise on wording.

However, the issue of assertion reuse may not be as cut-and-dry as it seems at first glance.  One example that has come up during test creation is that of "short" versus "long" assertion forms.  For instance:

1. When testing a simple control like a button, "Role 'button' is conveyed" is a clear, unambiguous assertion.  But...
2. When testing a tab within a tab list, a radio button within a group, etc., we presumably want to make it clear that there are multiple role-related assertions in a test, and allow testers to distinguish between them.  For example, "Role of the focused item, 'tab', is conveyed".

**Comment by mcking65** [comment]
Resolved by #974.
