### ISSUE TITLE
Should assertions have their own CSV file?

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#415]
With 6 assertions, tests.csv will currently have 15 headed columns.  That is approaching unfriendly spreadsheet territory for me, particularly given that the number of columns will grow with the number of assertions (some of our tests have 8, I think).

I propose that a new file be used, assertions.csv, with the following columns:

1. testId
2. assertion1
3. ...
4. assertionN

This would make tests.csv more manageable, particularly if some of the suggestions from #364 were implemented as well (e.g. to cut out the title column altogether).

**Comment by sinabahram** [comment]
This will also have other advantages like reducing git noise, potential conflicts due to topological changes in the original spreadsheet, and more. +1

**Comment by mcking65** [comment]
resolved by #974.
