### ISSUE TITLE
Document our Test Authorship and Test Runner Development Plan

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-at#42]
Myself and @spectranaut and others at Bocoup, in part based on information from @mcking65 , have put together a document that could be used as a starting point for a plan for test authorship and test runner development.

This is a Google Doc for now, which is public and anyone can comment and make suggestions. For archive purposes, I've sent [an HTML copy to www-archive@w3.org](https://lists.w3.org/Archives/Public/www-archive/2020Feb/0004.html). If we want to have a document like this for the CG, I think we should move it to the wiki for this repository.

The document is here:
https://docs.google.com/document/d/1nm4bIZf-lUnSon6LeUMxor1fjXk9TsZdcsxmCTOyIFM/edit?usp=sharing

**Comment by zcorpan** [comment]
@mcking65 @mfairchild365 can you review this?

**Comment by mfairchild365** [comment]
Yep, I'll add comments in the doc. Might be good to discuss on the CG call too.

**Comment by zcorpan** [comment]
I have updated phase 2, to align with Bocoup's engineering plan for the test runner, and per discussion with @mcking65 , to have a two test plans at a time review cadence for AT developers (instead of having a shorter review window for everything). Similarly for reviewing test results.

See https://github.com/w3c/aria-at/wiki/Test-Authorship-and-Test-Runner-Development-Plan

In particular, see [workstream 2.2](https://github.com/w3c/aria-at/wiki/Test-Authorship-and-Test-Runner-Development-Plan#work-stream-22-write-tests-and-run-pilot-before-end-of-development-phase). Will we have the first 2 test plans ready for review next week (April 6-10)?

**Comment by zcorpan** [comment]
https://www.w3.org/2020/04/08-aria-at-minutes.html#item03

I've pushed the dates out one week for test plan completion and review.

**Comment by mcking65** [comment]
completed work
