### ISSUE TITLE
Co-Design Workshop about tabular data on ARIA-AT App Reports Page

### ISSUE THREAD

**Issue by s3ththompson** [w3c/aria-at#437]
I’m excited to share an update about the co-design process, a project to involve a more diverse set of screen reader and assistive tech users in the design process for ARIA-AT and ARIA-AT App.

We are working with @NechariR, a professional facilitator, to host an initial 3-session workshop that will be a template for other co-design workshops in the future. The first two sessions will be 2-hour design meetings to propose solutions to a design challenge. The third session will be a 1-hour followup / feedback meeting to be scheduled after @bocoup can implement a prototype of the proposed solution.

The topic of the first workshop will be accessible design for the multi-dimensional tabular data behind the [ARIA-AT App Reports Page](https://aria-at.w3.org/reports). Over the next week or so, I’m looking forward to getting input from the community group on how to frame a meaningful, but reasonably-scoped problem statement for this page.

The first sessions of the workshop will be held on Tuesday, June 15 and Thursday, June 17 at a time to-be-determined.

We would like to keep the workshop intimate, but invite at least 2 community group members to participate. I think it might be nice to have a spot for a relatively new member of the community group and a spot for a more senior community group member.

Please let me know if you have any suggestions for who might be good representatives for the community group, ideally by next Friday, June 4.

**Comment by jscholes** [comment]
@s3ththompson Happy to represent the community group in whatever capacity is the most helpful.

**Comment by s3ththompson** [comment]
Coordinating schedules for the workshop sessions has been more difficult than expected. I've sent a (belated) invitation to @jscholes and @mcking65, but this first session is mostly a test of the workshop format with 3 non-community group members with a variety of screen reader expertises. If all goes well, we can hopefully apply the format to other topics going forward.

To that end, I'd like to share some ideas for how we can integrate the co-design workshop format into the CG process going forward (assuming the first one is successful!). @NechariR will help put together a facilitation template that covers the activities and structure of the workshop. Then for subsequent workshops we would need to:

- turn the workshop guide into a public (wiki?) template
- solicit possible topics from the community group and distill the topic into a concrete problem statement
- determine the best way to coordinate schedules between community group and non-community group members (especially considering that GitHub may or may not be a familiar tool to the types of participants we'd like to reach)
- work together to triage the feedback from the workshops into GitHub issues (Nechari has some plans for how to do this for this first workshop!)

I'll share a more concrete set of next steps after we have feedback from this first session.

**Comment by mcking65** [comment]
overcome by events; closing
