### ISSUE TITLE
Colons not correctly supported within assertions

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#456]
The [create-example-tests.js script](https://github.com/w3c/aria-at/blob/master/scripts/create-example-tests.js) uses the following code to determine the priority level (1 for required/2 for optional) of an assertion:

```
let parts = a.split(':');

if (parts.length === 2) {
  level = parts[0];
  str = parts[1].substring(0);
  if ((level != '1') && (level != '2')) {
    addTestError(test.testId, "Level value must be 1 or 2, value found was '" + level + "' for assertion '" + str + "' (NOTE: level 2 defined for this assertion).");
    level = '2';
  }
}
```

This works fine when the assertion text contains no colons.  But if it does, and an explicit priority level hasn't been included so that the default of "1:" will be inferred, the tests fail to be generated successfully.  For example the assertion:

> Name of the group is conveyed as: 'Choose a Date'

... results in an error like:

> [Test N]: Level value must be 1 or 2, value found was 'Name of the group is conveyed as' for assertion ': 'Choose a Date' (NOTE: level 2 defined for this assertion).

The work-around is to add "`1:`" to every assertion which is required (or those that contain a colon in their text), which is suboptimal.  The script really should only consider a colon in the second position when the first character is 1 or 2 (probably via a regexp).

**Comment by jscholes** [comment]
CC @s3ththompson, when do you think this could be addressed?  Probably quite a simple fix.

**Comment by s3ththompson** [comment]
@jscholes thanks for raising this. @richnoah and I will triage in sprint planning tomorrow. agreed that it looks like a simple fix.

**Comment by jscholes** [comment]
Fixed by https://github.com/w3c/aria-at/pull/458.
