### ISSUE TITLE
Replace support.json with key in references.csv

### ISSUE THREAD

**Issue by s3ththompson** [w3c/aria-at#471]
Right now test plans in the App Test Queue https://aria-at.w3.org/test-queue are showing up as directory names instead of human-readable names.

This is because they have not yet been added to the support.json file. The community group decided that this indirection was unnecessary and potentially confusing.

We should instead add human-readable names as a key in references.csv. The import test script in the app repo should be updated accordingly.

**Comment by howard-e** [comment]
> We should instead add human-readable names as a key in references.csv.

https://github.com/w3c/aria-at/pull/473 addresses this by first moving the existing titles. For the remaining titles, they could also be added to that branch.

> The import test script in the app repo should be updated accordingly.

https://github.com/w3c/aria-at-app/pull/320 accounts for this.

**Comment by jscholes** [comment]
When viewing the [Test Patterns for Review](https://w3c.github.io/aria-at/build/) page in this repo, the titles from `references.csv` aren't used in the "Pattern" column; the directory name is still used instead.  It would be good to fix that to close this issue out.

**Comment by mcking65** [comment]
completed
