### ISSUE TITLE
Tester's Issue Report For "Navigate backwards to a collapsed select-only combobox in reading mode"

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#477]
### Test File at exact Commit

[build/tests/combobox-select-only/test-02-navigate-backwards-to-collapsed-select-only-combobox-reading.html](https://aria-at.w3.org/aria-at/137716071d58d6d404d3dca45f8d6c12accb8388/build/tests/combobox-select-only/test-02-navigate-backwards-to-collapsed-select-only-combobox-reading.html?at=nvda)

### AT

Unless you navigate past the control, the shift+F, shift+C and the Up Arrow will never get to the combo box.
NVDA (version Latest)

### Browser

Firefox (version Latest)

### Description

_type your description here_

**Comment by jscholes** [comment]
@jongund The setup scripts for this test should set focus on the "Navigate backwards from here" link, facilitating these keystrokes.  Does this not work for you when you use the button to open the test page, and have you reproduced it multiple times?
