### ISSUE TITLE
After deleting a test run, could not start testing again

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#482]
I deleted my "combobox-select-only" test run and then pressed the "Start Testing" button to restart the testing process.
The button took me to a page thanking be for completing a test plan.
I had to un-assign myself and then re-assign myself to start the test plan again,

**Comment by richnoah** [comment]
@jongund that you for opening this issue.  I did test this in the staging environment and can confirm.  If you don't mind would you please open this issue in https://github.com/w3c/aria-at-app as it is specific to app development?  If not I can close this out and open it in that repos.
