### ISSUE TITLE
Tester's Issue Report For "Open a collapsed select-only combobox in reading mode"

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#500]
### Test File at exact Commit

[build/tests/combobox-select-only/test-10-open-collapsed-select-only-combobox-reading.html](https://aria-at.w3.org/aria-at/137716071d58d6d404d3dca45f8d6c12accb8388/build/tests/combobox-select-only/test-10-open-collapsed-select-only-combobox-reading.html?at=nvda)

### AT
Not sure the label "Favorite Fruit" for the combobox should be required to be spoken, seems like this could be optional

NVDA (version Latest)

### Browser

Firefox (version Latest)

### Description

_type your description here_

**Comment by jscholes** [comment]
@jongund The assertion relates to the name of the popup, i.e. the accessible name applied to the listbox.  That must be spoken when a screen reader moves from the combobox input to the popup, but it isn't asserting that the name applied to the combobox input itself is repeated.
