### ISSUE TITLE
Tester's Issue Report For "Read information about a listbox popup in interaction mode"

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#502]
### Test File at exact Commit

[build/tests/combobox-select-only/test-19-read-information-about-listbox-popup-interaction.html](https://aria-at.w3.org/aria-at/137716071d58d6d404d3dca45f8d6c12accb8388/build/tests/combobox-select-only/test-19-read-information-about-listbox-popup-interaction.html?at=nvda)

### AT

I think if needs to be clearer I should open the combobox, maybe including a suggested key press or I should be on a specific list item.
NVDA (version Latest)

### Browser

Firefox (version Latest)

### Description

_type your description here_

**Comment by jscholes** [comment]
@jongund This is, unfortunately, the same issue you've been experiencing within other tests.  There is a setup script that does open the combobox for the tester, and it places focus on the first item ("choose a fruit").  However, it seems that it isn't running reliably (or at all) for you.

**Comment by jongund** [comment]
I think it would help sighted testers if the test window was larger so we can see the effects of the start up script, at least in this example the default window size cuts off seeing the open listbox.
