### ISSUE TITLE
Exact scope of test plans

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#506]
### Test File at exact Commit

[build/tests/disclosure-navigation/test-07-navigate-forwards-to-expanded-disclosure-button-reading.html](https://aria-at.w3.org/aria-at/137716071d58d6d404d3dca45f8d6c12accb8388/build/tests/disclosure-navigation/test-07-navigate-forwards-to-expanded-disclosure-button-reading.html?at=jaws)

### AT
When in vritual mode and moving to an item in a differen landmark region, should the change in region be announced, I guess in general should changes in a group container also be announced?
JAWS (version Latest)

### Browser

Chrome (version Latest)

### Description

_type your description here_

**Comment by jscholes** [comment]
We started discussing this in the September 23 CG meeting.  It raised questions about exactly what is or is not in scope for a test/a test plan, which is a conversation we plan to revisit.  I will rename this issue to have a more specific title, and add the appropriate labels.
