### ISSUE TITLE
Tester's Issue Report For "Navigate backwards to an expanded disclosure button in reading mode"

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#507]
### Test File at exact Commit

[build/tests/disclosure-navigation/test-08-navigate-backwards-to-expanded-disclosure-button-reading.html](https://aria-at.w3.org/aria-at/137716071d58d6d404d3dca45f8d6c12accb8388/build/tests/disclosure-navigation/test-08-navigate-backwards-to-expanded-disclosure-button-reading.html?at=jaws)

### AT

For JAWS there may need to be a step saying press the control key to suppress automated reading of content in the new window, pressing the virtual navigation keys does not always stop the automated speaking of the page.

JAWS (version Latest)

### Browser

Chrome (version Latest)

### Description

_type your description here_

**Comment by jscholes** [comment]
@jongund This will be solved over the next few weeks.  A button will be added that must be explicitly pressed to execute the setup scripts.  So users will need to interrupt the automatic say-all to press the button.
