### ISSUE TITLE
Incorrect last link stated for test: "Navigate to the last link in a dropdown in interaction mode"

### ISSUE THREAD

**Issue by AlyssaGourley** [w3c/aria-at#569]
### Test File at Exact Commit

[test-41-navigate-to-last-link-in-dropdown-interaction-nvda.collected.html](https://aria-at.w3.org/aria-at/091420a186f267d6ed8f581dc0e8e168d194e709/build/tests/disclosure-navigation/test-41-navigate-to-last-link-in-dropdown-interaction-nvda.collected.html)

### AT

NVDA (version Latest)

### Browser

Firefox (version Latest)

### Description

_type your description here_In the criteria for the test, it says to go to the last link in the dropdown, which is "Campus Tours." However, the passing criteria states, "Name 'Overview' is conveyed." Should this be changed to "Name 'Campus TOurs' is conveyed?"

**Comment by jscholes** [comment]
Fixed in #583
