### ISSUE TITLE
Track which WAI-ARIA abstract roles are targeted by a test plan

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#579]
Currently, `references.csv` for each test plan only includes non-abstract WAI-ARIA roles.  But for example, by testing a slider, we are implicitly testing both `input` and `range`, which are `slider`'s superclass roles.  As a result of abstract roles not being recorded as references, we have no insight into how many abstract roles are targeted by our tests, and hence can never reach 100% of role coverage if the 100% is to include those abstract roles.

**Comment by mcking65** [comment]
@jscholes, I don't think we want to track coverage of abstract roles since authors cannot use them. Please feel free to re-open this issue if you have another perspective.
