### ISSUE TITLE
Track which WAI-ARIA roles, states and properties are implicitly targeted by a test plan

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#580]
Currently, `references.csv` for each test plan only includes non-abstract WAI-ARIA roles, states and properties, as stated by the "Role, Property, State, and Tabindex Attributes" section of the corresponding APG example.  When targeting a test case example that uses implicit semantics, for instance because it uses HTML elements where those semantics don't need to be explicitly specified, there will be no corresponding references.

As a practical example: a `<button>` element implies a role of `"button"`, and there is no need to add `role="button"` to it.  If testing such an element, `references.csv` will not include a link to the WAI-ARIA button role, nor to the relevant area of the HTML specification for `<button>`.  Indeed, other than metadata, the corresponding references file will be empty, unless some explicit ARIA usage is added to the button such as `aria-expanded`.

As a result of this, we have no insight into:

* how many roles, states and properties are implicitly  targeted by our tests; and
* how many HTML elements and attributes are covered by the project.

This may also limit our ability to demonstrate that 100% of role, state and property  coverage has been reached, if we reach that 100% coverage state by testing implicit semantics, at least in part.

**Comment by mcking65** [comment]
This is resolved by the new assertions.csv and references.csv specified by #974. Now, every assertion can have its own reference, and those references can include HTML AAM mappings. We could also add direct HTML spec references if appropriate.
