### ISSUE TITLE
Feedback: Invalid commands in "Navigate backwards to an expanded disclosure button in interaction mode" (Disclosure Navigation Menu Example, Test 10)

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#581]
## Description of Behavior

This test includes up arrow and left arrow. However, left arrow and up arrow do not navigate to the disclosure button in interaction mode if the focus is on a link in the controled/expanded content. Shift+Tab is the only command that should be included for this test.

In order to include left arrow, the initial focus would have to be on the second disclosure button instead of a link in the dropdown. However, if if initial focus were on the second button and the first button is expanded, then shift+tab would not go to the first button.

I recommend only testing shift+tab.

## Test Setup

- Test File at Exact Commit: [test-10-navigate-backwards-to-expanded-disclosure-button-interaction-jaws.collected.html](https://aria-at.w3.org/aria-at/091420a186f267d6ed8f581dc0e8e168d194e709/build/tests/disclosure-navigation/test-10-navigate-backwards-to-expanded-disclosure-button-interaction-jaws.collected.html)
- AT: JAWS (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Navigate backwards to an expanded disclosure button in interaction mode"

1.  ### Unexpected Behaviors for "Up Arrow" Command
    
    *   Tester jongund recorded output "nothing" and noted "silence".
    *   Tester louis4533 recorded output "no output" and noted no unexpected behavior.
2.  ### Unexpected Behaviors for "Left Arrow" Command
    
    *   Tester jongund recorded output "nothing" and noted "silence".
    *   Tester louis4533 recorded output "no output" and noted no unexpected behavior.
3.  ### Unexpected Behaviors for "Home" Command
    
    *   Tester jongund recorded output "nothing" and noted "silence".
    *   Tester louis4533 recorded output "no output" and noted no unexpected behavior.

**Comment by jscholes** [comment]
Fixed in #583
