### ISSUE TITLE
Tests fail to build when encountering UTF-8 byte order mark

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#590]
I'm attempting to build the tests in https://github.com/w3c/aria-at/pull/426, but the build job run is consistently failing with an unhelpful error (e.g. as seen in https://github.com/w3c/aria-at/runs/4695547690?check_suite_focus=true):

> TypeError: Cannot read property 'target' of undefined

I have no idea what this is refering to, and there is no additional context other than the stack trace:

```
(node:16656) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'target' of undefined
    at collectTestData (L:\Dropbox\Dev\aria-at\scripts\create-example-tests.js:1159:19)
    at L:\Dropbox\Dev\aria-at\scripts\create-example-tests.js:663:7
    at Array.map (<anonymous>)
    at L:\Dropbox\Dev\aria-at\scripts\create-example-tests.js:662:27
    at Array.flatMap (<anonymous>)
    at createExampleTests (L:\Dropbox\Dev\aria-at\scripts\create-example-tests.js:661:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async L:\Dropbox\Dev\aria-at\scripts\create-all-tests.js:65:55
    at async Promise.all (index 0)
    at async main (L:\Dropbox\Dev\aria-at\scripts\create-all-tests.js:63:3)
```

I added some debug logging in `create-example-tests.js`, and the output seems to suggest that the numeric test ID for the first task in the accordion plan isn't being detected for some reason:

```
{
  testId: NaN,
  task: 'navigate forwards to expanded accordion header',
  title: 'Navigate forwards to an expanded accordion header in reading mode',
...
```

I'm not sure why `testId` would be `NaN` here, but that seems to be the crux of the problem.  Without a test ID, the corresponding command row cannot be located.  However, I'm at a loss as to why `tests.csv` and/or `commands.csv` (the scripts don't tell me anything to help me work out which one) isn't/aren't being parsed correctly.  The column headers are set correctly (not even sure if that matters to the parsing or not), and I can't spot any issues with non-standard spacing, line breaks, etc.

Without anything more to go on, I'm effectively blocked from working on this test plan further right now.  CC @s3ththompson / @sinabahram

**Comment by jscholes** [comment]
Update: this was caused by the UTF-8 BOM being present in `commands.csv` and `tests.csv`, and I've updated the issue title accordingly.  I seem to remember this exact issue cropping up not too long ago, although I'm struggling to track down the exact issue or PR comment.

As this is a pretty obscure thing to figure out, and we know test writing will sometimes be driven by Excel that seems to add the BOM by default, it would be reasonable for the build process to detect this.  Whether it simply errors out with an informative message, or just ignores the BOM and works as expected, is a decision that should be made.  But I would vote for the latter, given that not all users will know how to remediate the problem, and providing exhaustive instructions is not a realistic proposition.

This is also related to https://github.com/w3c/aria-at/issues/537#issuecomment-954871244 and https://github.com/w3c/aria-at/pull/536; the build process doesn't exit when encountering this problem.

**Comment by SamuelHShaw** [comment]
@s3ththompson  Hi, just checking in from PAC to see if there are any updates on this, and possibly an ETA on when it may be able to be addressed?

**Comment by s3ththompson** [comment]
Hi @SamuelHShaw, as mentioned on the other thread the Bocoup office was closed last week for an all-hands. We're working through these issues as we can get to them since we're currently in the middle of the Q1 2022 planning process.

This issue seems to be a bit of a rabbit hole. As far as I can tell, it looks like it stems from Excel incorrectly inserting a BOM into UTF-8 files (based on how conversion between XLSX and CSV works)... I'm not sure yet whether it's appropriate to silently ignore the BOM mark, but it does seem like we should be able to at least warn when it's encountered.
