### ISSUE TITLE
Missing error handling for invalid reference rows

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#593]
When building tests, error handling is not implemented to inform test writers when an invalid row is encountered in `references.csv`, and assist them in fixing the problem.  For example, this row has three columns instead of two (the URL is accidentally repeated):

```
none,https://w3c.github.io/aria/#none,https://w3c.github.io/aria/#none
```

Upon attempting to parse this row, the build system outputs:

> TypeError: Cannot read property 'trim' of undefined

This doesn't indicate what the problem was, which reference row it related to, or even that there is a problem with the references file at all.

This is also related to https://github.com/w3c/aria-at/issues/537#issuecomment-954871244 and https://github.com/w3c/aria-at/pull/536; the build process doesn't exit when encountering this problem.

CC @s3ththompson

**Comment by SamuelHShaw** [comment]
@s3ththompson Hi, just checking in from PAC to see if there are any updates on this, and possibly an ETA on when it may be able to be addressed?
