### ISSUE TITLE
Build system output cluttered by Node warnings

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#594]
When building tests, the output is often cluttered by these Node warnings:

1. `(node:1762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`
2. `(node:1762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This makes the output more difficult to read, particularly when a warning is prepended in front of an error.  As this is clearly a known deprecation within Node, whichever coding techniques are triggering it should not be used.

CC @s3ththompson

**Comment by SamuelHShaw** [comment]
@s3ththompson  Hi, just checking in from PAC to see if there are any updates on this, and possibly an ETA on when it may be able to be addressed?

**Comment by howard-e** [comment]
> This makes the output more difficult to read, particularly when a warning is prepended in front of an error.

Agreed! The experience here is certainly bad when attempting to identify the error. #615 has been created to help with this and drastically reduce the noise.

> As this is clearly a known deprecation within Node, whichever coding techniques are triggering it should not be used.

The deprecation refers to the use of unhandled promises upon rejections. It seems the test review generation blocks were suitably covered based on some test writing assumptions. But in conjunction with #615 and other recently created PRs, it will certainly help mitigate this issue.
