### ISSUE TITLE
Non-unique link text on review page

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#599]
On the [Test Patterns for Review](https://w3c.github.io/aria-at/build/) page, each link in the "Index Page" and "Review Page" columns relates to a specific test plan.  However, each one has the same text ("Index" and "Review", respectively).  When combined with https://github.com/w3c/aria-at/issues/598, it is impossible for a screen reader user to quickly located a link relating to a pattern of interest without always navigating down the left-hand "Pattern" column first.

#### Suggested Solution

Use a combination of `aria-label` and `aria-labelledby` to give each link accessible names like: "Index: `<plan>`" and "Review: `<plan>`".

CC @s3ththompson

**Comment by SamuelHShaw** [comment]
@s3ththompson Hi, just checking in from PAC to see if there are any updates on this, and possibly an ETA on when it may be able to be addressed?
