### ISSUE TITLE
Feedback: "Open a collapsed select-only combobox in reading mode" (Select Only Combobox Example, Test 10)

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#638]
@mfairchild365 
## Description of Behavior

Do we have the correct assertions for this test.
In a standard select box NVDA on Firefox announces the role as "combobox" (.e.g. not listbox) and does not provide any information about the length or position of the item in the list of options.

## Test Setup

- Test File at Exact Commit: [test-10-open-collapsed-select-only-combobox-reading-nvda.collected.html](https://aria-at.w3.org/aria-at/091420a186f267d6ed8f581dc0e8e168d194e709/build/tests/combobox-select-only/test-10-open-collapsed-select-only-combobox-reading-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Firefox (version Latest)

## Review Conflicts for "Open a collapsed select-only combobox in reading mode"

1.  ### Assertion Results for "Alt+Down" Command and "Role of the popup ('listbox') is conveyed" Assertion
    
    *   Tester jongund recorded output "expanded Favorite Fruit list Choose a Fruit 1 of 13" and marked assertion as passing.
    *   Tester jha11y recorded output "expanded Favorite Fruit list Choose a Fruit 1 of 13" and marked assertion as failing with incorrect output.

**Comment by jscholes** [comment]
> In a standard select box NVDA on Firefox announces the role as "combobox" (.e.g. not listbox) and does not provide any information about the length or position of the item in the list of options.

I can't reproduce this.  When I access the examples at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select with Firefox and NVDA, and specifically when I press Alt+Down Arrow to open the select, the role is reported as "list".  Which, granted, is not listbox, but it fits the standard NVDA behaviour of identifying listboxes as lists, and also matches how the screen reader behaves for the custom version being tested here.  Firefox does give the listbox an accessible name matching the selected value, which seems wrong.  But, we're also not testing a native `<select>` in this plan, so probably also irrelevant.

Let me know if I'm misunderstanding your feedback, and/or if you're experiencing different behaviour.

**Comment by jscholes** [comment]
Additional note: once the native `select` has been opened with Alt+Down Arrow, NVDA does convey the position of each item in the list, and the total.

**Comment by jha11y** [comment]
Jon I believe what you say is correct. So possibly the assertion is wrong?

**Comment by jscholes** [comment]
@jha11y Could you expand on which assertion(s) you believe to be wrong, and the corresponding reasons?  My comments were intended to indicate that I believe the assertions to be correct.

**Comment by jha11y** [comment]
@jscholes nevermiond. On today's call we agreed that NVDA announcing "List" was acceptable for the assertion "Role of the popup ('listbox') is conveyed".

**Comment by jscholes** [comment]
@jha11y Great, thanks for that update.  In that case, I think this issue can be closed.  Let me know if you disagree!
