### ISSUE TITLE
Broken links to https://w3c.github.io/aria-at/

### ISSUE THREAD

**Issue by howard-e** [w3c/aria-at#677]
In addition to #675, there are 2 other links used in the project which need to be updated, however it doesn't seem those links existed before.

> README.md under Get Involved
[Reviewing assertions of existing test plans](https://w3c.github.io/aria-at/review-test-plans/)

It doesn't seem this link existed before. Should it point to https://w3c.github.io/aria-at?

> .github/ISSUE_TEMPLATE/test-plan.md (New issue -> Create a new test plan for APG design pattern)
[Test results](https://w3c.github.io/aria-at/results/)

It doesn't seem like this link existed before. But it also doesn't seem like the overall structure of this issue template is being used anymore. Should we update this template with what is currently being done when creating new test plans? https://github.com/w3c/aria-at/issues?q=is%3Aissue+author%3AIsaDC+Create+tests+for+APG+design+pattern+ ie.
> **Applies To**
**Testing Notes**
**Additional References**

**Comment by howard-e** [comment]
cc @s3ththompson @richnoah

**Comment by mcking65** [comment]
The readme is basically all out of date. We do not want to duplicate content, so I think the readme should point to the home page of aria-at.w3.org. It should have just a couple sentences explaining content of the repo and then tell people to learn more and get involved by going to aria-at.w3.org.

We should keep the bit about running locally. I don't know if that page on running locally is up-to-date.

We should not point to the home page of the wiki; that needs to be fixed up too.

**Comment by richnoah** [comment]
@mcking65 will you please provide some direction on your last point about not pointing to the home page of the wiki.  Are you requesting that section be removed or should the section remain but the URL point to a different location?

**Comment by mcking65** [comment]
resolved
