### ISSUE TITLE
Bug: preview page doesn't display test plan titles

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#689]
A `title` field was added to `references.csv` in 2021, to allow a human-readable name for each plan to be directly specified.  While the ARIA-AT App utilises this field, the preview page does not.  This means that audiences relying on the preview facility for review purposes (such as AT vendors) are presented with the raw folder names instead of the intended titles.  Reproduce:

1. Open https://aria-at.netlify.app/.
2. In the first column of the table, observe that directory names are used, e.g. "combobox-autocomplete-both-updated" rather than "Combobox with Both List and Inline Autocomplete Example".

CC @s3ththompson / @richnoah / @mcking65

**Comment by mcking65** [comment]
fixed
