### ISSUE TITLE
Wording in Instruction Step 4 in task "Navigate backwards to a menu button in reading mode" (Navigation Menu Button, Test 4)

### ISSUE THREAD

**Issue by AlyssaGourley** [w3c/aria-at#714]
## Description of Behavior
In step 4 under "Test Instructions, the instruction says "With the reading cursor on the 'Navigate forwards from here' link..." Since we're navigating backwards, we should instead be focusing first on the "Navigate backwards from here" link, which is where setup sets the focus.

## Test Setup

- Test File at Exact Commit: [test-04-navigate-backwards-to-a-menu-button-reading-jaws.collected.html](https://aria-at.w3.org/aria-at/7ec8fa91c8bde5af1fe7ff78698fcf1c737af1b2/build/tests/menu-button-navigation/test-04-navigate-backwards-to-a-menu-button-reading-jaws.collected.html)
- AT: JAWS (version Latest)
- Browser: Chrome (version Latest)

**Comment by AlyssaGourley** [comment]
This also occurs on the "Navigate backwards to a menu button in interaction mode" test.

**Comment by jscholes** [comment]
@AlyssaGourley Good catch!  Thanks for this; all instances should now be fixed.
