### ISSUE TITLE
Conflict: Navigation Menu Button, role of "Menu Item" not conveyed when opening the menu and encountering the first item

### ISSUE THREAD

**Issue by AlyssaGourley** [w3c/aria-at#715]
## Description of Behavior
Browser and AT versions:
Chrome: 101.0.4951.67 (Official Build) (64-bit) (cohort: Stable) 
JAWS: Version 2022.2204.20 ILM  

Issue:
I receive the following output when opening the menu:
"WAI-ARIA Quick Links menu W3C Home Page 1 of 6" 
From my understanding of the criteria, JAWS is supposed to announce "W3C Home Page" as a "menu item" along with the other information such as the position and number of items. I'm wondering how this can pass if JAWS never says "Menu Item" for any of these items. Shouldn't the output be something like, "W3C Home Page Menu Item 1 of 6?"

## Test Setup

- Test File at Exact Commit: [test-10-open-a-menu-reading-jaws.collected.html](https://aria-at.w3.org/aria-at/7ec8fa91c8bde5af1fe7ff78698fcf1c737af1b2/build/tests/menu-button-navigation/test-10-open-a-menu-reading-jaws.collected.html)
- AT: JAWS (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Open a menu in reading mode"

1.  ### Assertion Results for "Space" Command and "Role of the focused item, 'menu item', is conveyed" Assertion
    
    *   Tester louis4533 recorded output "WAI-ARIA Quick Links menu W3C Home Page 1 of 6 To move through items press up or down arrow." and marked assertion as passing.
    *   Tester AlyssaGourley recorded output "WAI-ARIA Quick Links menu W3C Home Page 1 of 6 To move through items press up or down arrow." and marked assertion as failing with no output.
    *   Tester IsaDC recorded output "WAI-ARIA Quick Links menu W3C Home Page 1 of 6 To move through items press up or down arrow." and marked assertion as passing.
2.  ### Assertion Results for "Enter" Command and "Role of the focused item, 'menu item', is conveyed" Assertion
    
    *   Tester louis4533 recorded output "WAI-ARIA Quick Links menu W3C Home Page 1 of 6 To move through items press up or down arrow." and marked assertion as passing.
    *   Tester AlyssaGourley recorded output "WAI-ARIA Quick Links menu W3C Home Page 1 of 6 To move through items press up or down arrow." and marked assertion as failing with no output.
    *   Tester IsaDC recorded output "WAI-ARIA Quick Links menu W3C Home Page 1 of 6 To move through items press up or down arrow." and marked assertion as passing.
    *

**Comment by AlyssaGourley** [comment]
The same conflicts apply to the "Open a menu in interaction mode" and "Open a menu to the last item in interaction mode" tests.

**Comment by IsaDC** [comment]
@AlyssaGourley  Thank you for creating this issue.

@louis4533 In line with results from other testers, and consensus reached during a recent Community Group meeting, I have altered your passing assertion relating to the role of menu item to a failed status.  This is because the indication of the presence of menu items in your output was based on the content of a help message.  As these can be disabled by the user, and often are, they are not in scope for meeting assertions.
