### ISSUE TITLE
Feedback: "Read information about a link in reading mode" (Link Example 1 (span element with text content), Test 7)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#718]
## Test Setup

- Test File at Exact Commit: [test-07-read-information-about-a-link-reading-nvda.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/link-span-text/test-07-read-information-about-a-link-reading-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Read information about a link in reading mode"

1.  ### Unexpected Behaviors for "Insert+Tab" Command
    
    *   Tester IsaDC recorded output "W3C website link focused linked " and noted no unexpected behavior.
    *   Tester jha11y recorded output "W3C website link focused linked" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".
    *   Tester louis4533 recorded output "W3C website link focused linked" and noted no unexpected behavior.

**Comment by IsaDC** [comment]
Outcome of the Community Group meeting of May 26, 2022: this conflict will be resolved by checking the "Output is excessively verbose ..." checkbox within the results that don't currently record that outcome.  It was felt that NVDA's internal tracking of a linked state, in addition to a link role, provides little-to-no utility for users, and hence is considered redundant.  NVAccess will have an opportunity to comment on this decision once the test plan is moved to the Candidate phase, at which point it may be revisited given appropriate justification and/or context.
