### ISSUE TITLE
Feedback: "Close a modal dialog in reading mode" (Modal Dialog Example, Test 4)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#719]
## Test Setup

- Test File at Exact Commit: [test-04-close-a-modal-dialog-reading-nvda.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/modal-dialog/test-04-close-a-modal-dialog-reading-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Close a modal dialog in reading mode"

1.  ### Unexpected Behaviors for "Escape" Command
    
    *   Tester jha11y recorded output "button unavailable Run Test Setup Add Delivery Address button" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".
    *   Tester IsaDC recorded output "Add Delivery Address button " and noted no unexpected behavior.
    *   Tester louis4533 recorded output "Add Delivery Address button " and noted no unexpected behavior.

**Comment by IsaDC** [comment]
@jha11y Were you able to reproduce this unexpected behavior multiple times? If not, please try rerunning the test a few times. If it happens consistently, let me know on this issue and we will look into it further.  Otherwise, it may have been a one-off, and we will probably be able to just remove the indication of excessive verbosity.

**Comment by jha11y** [comment]
I retested twice and I got the same feedback and closing the Screen reader and the browser.  I will restart my test machine and test again tomorrow, but chrome could update in the background. I will not update NVDA.

**Comment by jha11y** [comment]
I tested multiple times by closing NVDA and Chrome during my original testing.  I was able to replicate the results after a system restart today. Chrome updated to Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by jscholes** [comment]
@IsaDC 

1. Update the test plan version in the test queue.
2. Have all three testers re-run the relevant test.
3. Manually make sure that the same undesirable behaviours are recorded for each result.

**Comment by mcking65** [comment]
Out-of-date due to test plan refactor
