### ISSUE TITLE
Feedback: "Close a modal dialog in interaction mode" (Modal Dialog Example, Test 5)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#720]
## Test Setup

- Test File at Exact Commit: [test-05-close-a-modal-dialog-interaction-nvda.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/modal-dialog/test-05-close-a-modal-dialog-interaction-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Close a modal dialog in interaction mode"

1.  ### Unexpected Behaviors for "Escape" Command
    
    *   Tester jha11y recorded output "None unless escape is hit twice, then: button unavailable Run Test Setup Add Delivery Address button " and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".
    *   Tester IsaDC recorded output """" and noted no unexpected behavior.
    *   Tester louis4533 recorded output "Add Delivery Address button " and noted "I had to press escape twice. Once to exit focus mode, and a 2nd time to close the dialog.".
2.  ### Assertion Results for "Escape" Command and "Role 'button' is conveyed" Assertion
    
    *   Tester jha11y recorded output "None unless escape is hit twice, then: button unavailable Run Test Setup Add Delivery Address button " and marked assertion as passing.
    *   Tester IsaDC recorded output """" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "Add Delivery Address button " and marked assertion as passing.
3.  ### Assertion Results for "Escape" Command and "Name 'Add Delivery Address' is conveyed" Assertion
    
    *   Tester jha11y recorded output "None unless escape is hit twice, then: button unavailable Run Test Setup Add Delivery Address button " and marked assertion as passing.
    *   Tester IsaDC recorded output """" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "Add Delivery Address button " and marked assertion as passing.

**Comment by jha11y** [comment]
The test case #4 for the modal dialog (Testing Task: Close a modal dialog in interaction mode) is flawed.  A user can get different results depending on how many times the hit the escape key.  Also, for this test when activating the "Run Test Setup" button, the dialog automatically opens.  This is different behavior from tasks #1 and #2, but the same as #3.  The inconsistency between tasks is very confusing.

**Comment by IsaDC** [comment]
@jha11y The Community Group has previously reached consensus that in interaction mode, a screen reader should pass the Escape key through to the page.  I know that this can be seen as subjective, but the test was written with this decision in mind.  As such, please rerun the test, pressing Escape only once as instructed.  If the results do not pass the assertions (which we know they wont), mark the assertions as failing.

Note: there is a chance that if/when these tests are reviewed by NVAccess during a future phase, they will disagree with the test as it is currently written.  If so, this decision may need to be revisited.

**Comment by jha11y** [comment]
@IsaDC I fine with that. I can update my results

**Comment by mcking65** [comment]
Out-of-date due to test plan refactor
