### ISSUE TITLE
Feedback: "Close a nested modal dialog in interaction mode" (Modal Dialog Example, Test 14)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#723]
## Test Setup

- Test File at Exact Commit: [test-22-close-a-nested-modal-dialog-interaction-nvda.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/modal-dialog/test-22-close-a-nested-modal-dialog-interaction-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Close a nested modal dialog in interaction mode"

1.  ### Unexpected Behaviors for "Escape" Command
    
    *   Tester IsaDC recorded output "Add Delivery Address button Verify Address button " and noted no unexpected behavior.
    *   Tester jha11y recorded output "Add Delivery Address dialog Verify Address button Add Delivery Address button Verify Address button Add button Cancel" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".
    *   Tester louis4533 recorded output "Add Delivery Address dialog Verify Address button Add Delivery Address " and noted no unexpected behavior.

**Comment by IsaDC** [comment]
Related to #719: @jha11y  is this something you can reproduce consistently?

**Comment by jha11y** [comment]
I retested twice and I got the same feedback and closing the Screen reader and the browser.  I will restart my test machine and test again tomorrow, but chrome could update in the background. I will not update NVDA.

**Comment by jha11y** [comment]
I was able to replicate the results after a system restart. Chrome updated to Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by mcking65** [comment]
Out-of-date due to test plan refactor
