### ISSUE TITLE
Feedback: "Open a nested modal dialog using a link in reading mode" (Modal Dialog Example, Test 17)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#726]
## Test Setup

- Test File at Exact Commit: [test-27-open-a-nested-modal-dialog-using-a-link-reading-nvda.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/modal-dialog/test-27-open-a-nested-modal-dialog-using-a-link-reading-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Open a nested modal dialog using a link in reading mode"

1.  ### Unexpected Behaviors for "Enter" Command
    
    *   Tester IsaDC recorded output "End of the Road! dialog You activated a fake link or button that goes nowhere! The link or button is present for demonstration purposes only. Close button " and noted no unexpected behavior.
    *   Tester louis4533 recorded output "End of the Road! dialog You activated a fake link or button that goes nowhere! The link or button is present for demonstration purposes only. Close button End of the Road! " and noted no unexpected behavior.
    *   Tester jha11y recorded output "End of the Road! dialog You activated a fake link or button that goes nowhere! The link or button is present for demonstration purposes only. Close button End of the Road! button Close" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".

**Comment by IsaDC** [comment]
Related to #719: @jha11y  is this something you can reproduce consistently?

**Comment by jha11y** [comment]
I retested twice and I got the same feedback and closing the Screen reader and the browser.  I will restart my test machine and test again tomorrow, but chrome could update in the background. I will not update NVDA.

**Comment by jha11y** [comment]
I was able to replicate the results after a system restart. Chrome updated to Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by mcking65** [comment]
out-of-date due to test plan refactor
