### ISSUE TITLE
Feedback: "Navigate to the beginning of a modal dialog in reading mode" (Modal Dialog Example, Test 14)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#732]
## Description of Behavior

See #731

## Test Setup

- Test File at Exact Commit: [test-14-navigate-to-the-beginning-of-a-modal-dialog-reading-jaws.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/modal-dialog/test-14-navigate-to-the-beginning-of-a-modal-dialog-reading-jaws.collected.html)
- AT: JAWS (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Navigate to the beginning of a modal dialog in reading mode"

1.  ### Unexpected Behaviors for "Control+Home, then Down Arrow" Command
    
    *   Tester IsaDC recorded output "Modal Dialog Example main region" and noted "I had to get JAWS out of formes mode and then press the commands. However, JAWS needs 2 down arrow to land on the heading.".
    *   Tester louis4533 recorded output "main region" and noted "Forms mode was automatically activated with focus placed on the Street: edit field. I had to press escape in order to exit forms mode before being able to type the testing key sequence (Control+Home, then Down Arrow).".

**Comment by IsaDC** [comment]
Apologies, this issue is a duplicate of #731

**Comment by mcking65** [comment]
Resolved by refactor
