### ISSUE TITLE
Feedback: "Navigate out of the start of a radio group" (Radio Group Example Using aria-activedescendant, Test 19)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#744]
## Description of Behavior
The Shift+Tab command did not navigate backwards for two testers.  See also #745 

## Test Setup

- Test File at Exact Commit: [test-19-navigate-out-of-the-start-of-a-radio-group-interaction-voiceover_macos.collected.html](https://aria-at.w3.org/aria-at/9d53c205c877970620ff5a13afb1e410ff6f1652/build/tests/radiogroup-aria-activedescendant/test-19-navigate-out-of-the-start-of-a-radio-group-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version Latest)
- Browser: Safari (version Latest)

## Review Conflicts for "Navigate out of the start of a radio group"

1.  ### Unexpected Behaviors for "Shift+Tab" Command
    
    *   Tester louis4533 recorded output "no speech output" and noted "Shift+Tab did not navigate backwards. Focus remained unchanged.".
    *   Tester IsaDC recorded output """" and noted "The command sequence did not seem to have any effect.".
    *   Tester jongund recorded output "link Navigate forwards from here main You are currently on a link. To click this link, press Control-Option-Space." and noted no unexpected behavior.
2.  ### Assertion Results for "Shift+Tab" Command and "Role 'link' is conveyed" Assertion
    
    *   Tester louis4533 recorded output "no speech output" and marked assertion as failing with no output.
    *   Tester IsaDC recorded output """" and marked assertion as failing with no output.
    *   Tester jongund recorded output "link Navigate forwards from here main You are currently on a link. To click this link, press Control-Option-Space." and marked assertion as passing.
3.  ### Assertion Results for "Shift+Tab" Command and "name 'Navigate forwards from here' is conveyed" Assertion
    
    *   Tester louis4533 recorded output "no speech output" and marked assertion as failing with no output.
    *   Tester IsaDC recorded output """" and marked assertion as failing with no output.
    *   Tester jongund recorded output "link Navigate forwards from here main You are currently on a link. To click this link, press Control-Option-Space." and marked assertion as passing.

**Comment by jscholes** [comment]
@jongund On the "Advanced" tab of Safari Preferences, do you have the option to "highlight each item in a webpage" using Tab enabled?

**Comment by mfairchild365** [comment]
I can reproduce the no speech output if the "press tab to highlight each item on a webpage" is unchecked in safari preferences (under the advanced tab). 

I can reproduce jongund's results if the same setting is checked.

**Comment by jscholes** [comment]
@cookiecrook Is it Apple's expectation that all VoiceOver users should have this advanced Safari preference (relating to Tab moving focus through page elements) enabled, in order for VO to work correctly on web pages?

**Comment by cookiecrook** [comment]
On mobile atm, but IIRC, the behavioral difference is listed on that preference checkbox. If the user does not have that setting checked, it’d be Shift+Opt+Tab, instead of Shift+Tab.

**Comment by jscholes** [comment]
@IsaDC Resolution: tests need to be re-run with this setting enabled.

**Comment by IsaDC** [comment]
Conflicts will be addressed by re-running tests.
