### ISSUE TITLE
Feedback: "Navigate out of the end of a radio group" (Radio Group Example Using aria-activedescendant, Test 22)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#745]
## Description of Behavior

See #744 

## Test Setup

- Test File at Exact Commit: [test-22-navigate-out-of-the-end-of-a-radio-group-interaction-voiceover_macos.collected.html](https://aria-at.w3.org/aria-at/9d53c205c877970620ff5a13afb1e410ff6f1652/build/tests/radiogroup-aria-activedescendant/test-22-navigate-out-of-the-end-of-a-radio-group-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version Latest)
- Browser: Safari (version Latest)

## Review Conflicts for "Navigate out of the end of a radio group"

1.  ### Unexpected Behaviors for "Tab" Command
    
    *   Tester louis4533 recorded output "no speech" and noted "Tab did not navigate out of the radio group. Focus is unchanged.".
    *   Tester IsaDC recorded output """" and noted "The command follows the behavior of shift+Tab".
    *   Tester jongund recorded output "link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space. " and noted no unexpected behavior.
2.  ### Assertion Results for "Tab" Command and "Role 'link' is conveyed" Assertion
    
    *   Tester louis4533 recorded output "no speech" and marked assertion as failing with no output.
    *   Tester IsaDC recorded output """" and marked assertion as failing with no output.
    *   Tester jongund recorded output "link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as passing.
3.  ### Assertion Results for "Tab" Command and "name 'Navigate backwards from here' is conveyed" Assertion
    
    *   Tester louis4533 recorded output "no speech" and marked assertion as failing with no output.
    *   Tester IsaDC recorded output """" and marked assertion as failing with no output.
    *   Tester jongund recorded output "link Navigate backwards from here main You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as passing.

**Comment by jscholes** [comment]
See #744 for further discussion.

**Comment by IsaDC** [comment]
Conflicts will be addressed by re-running tests.
