### ISSUE TITLE
Feedback: "Decrement a slider to the minimum value" (Color Viewer Slider, Test 19)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#747]
## Description of Behavior

See unexpected behaviours below and #748 .

## Test Setup

- Test File at Exact Commit: [test-19-decrement-slider-to-minimum-value-interaction-voiceover_macos.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/horizontal-slider/test-19-decrement-slider-to-minimum-value-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version Latest)
- Browser: Safari (version Latest)

## Review Conflicts for "Decrement a slider to the minimum value"

1.  ### Unexpected Behaviors for "Home" Command
    
    *   Tester IsaDC recorded output "heading level 3 Color Viewer" and noted "The value changes to 0, but VoiceOver reads "heading level 3 Color Viewer"".
    *   Tester jongund recorded output "heading level 3 Color Viewer" and noted "no information about change in slider value".
    *   Tester louis4533 recorded output "heading level 3 Color Viewer" and noted "Reviewing the page after the Home command shows that the color was changed to green from red, rather than the expected change of the slider being set to 0.".
2.  ### Assertion Results for "Home" Command and "Value '0' is conveyed" Assertion
    
    *   Tester IsaDC recorded output "heading level 3 Color Viewer" and marked assertion as failing with incorrect output.
    *   Tester jongund recorded output "heading level 3 Color Viewer" and marked assertion as failing with incorrect output.
    *   Tester louis4533 recorded output "heading level 3 Color Viewer" and marked assertion as failing with no output.

**Comment by jscholes** [comment]
@IsaDC Resolution: remove all indications of unexpected behaviours, and change @louis4533's assertions to "incorrect output".

**Comment by IsaDC** [comment]
The described changes have been made.
