### ISSUE TITLE
Feedback: "Increment a slider to the maximum value" (Color Viewer Slider, Test 21)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#748]
## Description of Behavior

VoiceOver conveys the initial value multiple times after speaking the maximum value.  See also #747 

## Test Setup

- Test File at Exact Commit: [test-21-increment-slider-to-maximum-value-interaction-voiceover_macos.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/horizontal-slider/test-21-increment-slider-to-maximum-value-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version Latest)
- Browser: Safari (version Latest)

## Review Conflicts for "Increment a slider to the maximum value"

1.  ### Unexpected Behaviors for "End" Command
    
    *   Tester IsaDC recorded output " 255, 128, 128" and noted "VoiceOver repeated the number 128 twice after conveying the maximum value.".
    *   Tester jongund recorded output "255, 128, 128" and noted "seems to be reading output value and not slider".
    *   Tester louis4533 recorded output "255, 128, 128 Color (RGB): text" and noted no unexpected behavior.

**Comment by jscholes** [comment]
@IsaDC Same resolution as #747.

**Comment by IsaDC** [comment]
The described changes have been made.
