### ISSUE TITLE
Feedback: "Navigate forwards to a not pressed toggle button in reading mode" (Toggle Button, Test 1)

### ISSUE THREAD

**Issue by RFischer-FS** [w3c/aria-at#786]
## Description of Behavior

I can also not open the test example for the Toggle Button. I receive the error 404: Not Found.

## Test Setup

- Test File: [test-01-navigate-forwards-to-not-pressed-toggle-button-reading-jaws.collected.html](https://aria-at.netlify.app/tests/toggle-button/test-01-navigate-forwards-to-not-pressed-toggle-button-reading-jaws.collected.html)
- AT: JAWS (version undefined)
- Browser: Chrome (version undefined)

**Comment by RFischer-FS** [comment]
Yes, it works now. Thank you.

**Comment by jscholes** [comment]
@RFischer-FS Thanks for confirming the new, working behaviour.  I'll close this issue as complete; please feel free to open new tickets or comment on https://github.com/w3c/aria-at/issues/785 as you continue your review process.
