### ISSUE TITLE
Investigate open source test management packages

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-at#8]
It's possible an open source management software could be used to provide a web interface for tests instead of rolling our own. I'd like to keep track of a list of requirements while I research some, so please chime!

List of requirements, as I understand them now:
* Presentation of test and assertions should be configurable (such as the discussion in issue: https://github.com/w3c/aria-at/issues/6)
* Should be able to upload test into the software (tests authored by this community group) 
* Should be able to configure custom data or meta data in the test result.
* Should be able to export test results
* Log in/accounts for testers

**Comment by mfairchild365** [comment]
Comments from the call today: 

* How customizable is the data collection? Can you customize all the fields and the order in which they are asked?
* Can we collect the output from the screen reader? (would be amazing if this could be automated, via a braille driver or plugin)
* Can we collect the input commands (would also be amazing if this could be automated)
* Can we have branching capabilities in the data collection form? For example, if the output was good, display a simple form. Otherwise, we might need to ask more questions.

**Comment by spectranaut** [comment]
@mcking65 and anyone else, has there been a discussion of who will cover the cost of hosting or subscription for project?

**Comment by mcking65** [comment]
* How accessible is the UI out of the box? This might be a good path of inquiry for CG members to investigate rather than using Bocoup time.
* If we would like to make accessibility or other improvements to the UI, how difficult will that be?

**Comment by mcking65** [comment]
> @mcking65 and anyone else, has there been a discussion of who will cover the cost of hosting or subscription for project?

Top choice is open source with a license that we can use for free. Unless there is very significant advantage, we probably do not want to buy a subscription.

We have the challenge that we would like to have a variety of testers, none of whom will be full time on the project for more than a few days or weeks at a time. So, a per user subscription could end up being lots of management overhead.

As far as hosting, I hope we would be able to run it all from github. If we need something else, we can investigate options.

**Comment by mcking65** [comment]
Here is one site about open source test management software I started browsing through when we first started discussing this option:

http://www.opensourcetestmanagement.com/

**Comment by corbb** [comment]
One option that comes to mind that’s highlg scriptable and customizable: https://airtable.com/

**Comment by spectranaut** [comment]
From this issue and [today's meeting](https://www.w3.org/2019/10/09-aria-at-minutes.html) I began a [feature requirements wiki page](https://github.com/w3c/aria-at/wiki/Test-Harness-Feature-Requirements). I think we haven't covered all requirements, feel free to chime in here for more!

**Comment by spectranaut** [comment]
Investigation has been completed.
