### ISSUE TITLE
Feedback: "Navigate to the last breadcrumb link" (Breadcrumb Example, Test 6)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#810]
## Description of Behavior

Is the last item in a set of breadcrumbs supposed to be a link?  If so, in the example the last breadcrumb "link" does not look like a link and is visually dissimilar to the other breadcrumb links.

## Test Setup

- Test File: [test-06-navigate-to-the-last-breadcrumb-link-interaction-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/breadcrumb/test-06-navigate-to-the-last-breadcrumb-link-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version 12.5.1)
- Browser: Safari (version 15.6.1)

## Review Conflicts for "Navigate to the last breadcrumb link"

1.  ### Unexpected Behaviors for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".
    *   Tester jha11y recorded output "current page, link, Breadcrumb Example, 4 of 4" and noted no unexpected behavior.
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and noted no unexpected behavior.
2.  ### Assertion Results for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command and "Role of the landmark region, 'navigation', is conveyed" Assertion
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as passing.
    *   Tester jha11y recorded output "current page, link, Breadcrumb Example, 4 of 4" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and marked assertion as passing.
3.  ### Assertion Results for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command and "Name of the landmark region, 'Breadcrumb', is conveyed" Assertion
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as passing.
    *   Tester jha11y recorded output "current page, link, Breadcrumb Example, 4 of 4" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and marked assertion as passing.
4.  ### Assertion Results for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command and "Role of the breadcrumbs container, 'list', is conveyed" Assertion
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as passing.
    *   Tester jha11y recorded output "current page, link, Breadcrumb Example, 4 of 4" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and marked assertion as passing.
5.  ### Assertion Results for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command and "Number of list items, 4, is conveyed" Assertion
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as failing with no output.
    *   Tester jha11y recorded output "current page, link, Breadcrumb Example, 4 of 4" and marked assertion as passing.
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and marked assertion as passing.

**Comment by jscholes** [comment]
@jha11y Thanks for the feedback.  The last breadcrumb in the trail is marked up as a link, and this test plan evaluates support for the semantics accordingly.

If you feel that there is a usability and/or accessibility issue exhibited by the example itself, e.g. because the last link doesn't look like an interactive element, please file an issue on the [aria-practices repo](https://github.com/w3c/aria-practices).  I'll close this one, as there is nothing to be changed within an ARIA-AT test.

**Comment by jha11y** [comment]
no that makes sense if the ARIA-AT example is following the authoring practices then this is good.
