### ISSUE TITLE
Feedback: "Navigate forwards to a heading inside a main landmark" (Main Landmark, Test 14)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#812]
## Description of Behavior

For tests that are testing assertions that include roles (main or heading), these words should not be included in the text content of the example because this can be confusing to differentiate the roles from the text content.

## Test Setup

- Test File: [test-14-navigate-forwards-to-a-heading-inside-a-main-landmark-interaction-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/main/test-14-navigate-forwards-to-a-heading-inside-a-main-landmark-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version 12.5.1)
- Browser: Safari (version 15.6.1)

**Comment by jscholes** [comment]
@mcking65 Raising this issue for CG discussion.

**Comment by jscholes** [comment]
@jha11y Thanks for this feedback!  Following discussion during the CG meeting of December 1st, 2022, two main points were raised in response:

1. We assume a certain level of familiarity with the screen reader under test, in terms of how it conveys information.  This should hopefully protect against testers incorrectly understanding one piece of output as another, and related issues.  If any tester is ever unsure, providing this sort of feedback and asking for help is fully encouraged.  This is also one of the reasons behind at least two sets of results being required at various points along the Working Mode timeline.
2. If the underlying example needs to be changed, this will be a potential future concern for the APG Taskforce.  The ARIA-AT tests will then be updated accordingly, if/when that happens.

With this in mind, we won't be expending bandwidth on changing the test plan at this time.  Let us know if you have concerns with this decision.

Thanks!
