### ISSUE TITLE
Rundown: Review of three tests (menubar,checkbox,combobox) 

### ISSUE THREAD

**Issue by Yohta89** [w3c/aria-at#84]
Reading the posts on review, I think they could be classified into several categories:

- Consistency > It seems most important to me, but mostly judgment call.
- Command > I think this is something we want to discuss in the meeting instead of posts.
- Language 
- Technical bug > I think this could be discussed through GitHub postings if we ran out of time.

Based on this classification I made a very quick rundown that summarized review posts done by Matt, Michael, and me (attached) , hoping to facilitate the upcoming meeting. 
*The document doesn't include obvious issues such as missing commands or things already agreed in the checkbox issued between Matt and Michael.

[0226_test_rundown.xlsx](https://github.com/w3c/aria-at/files/4257774/0226_test_rundown.xlsx)

**Link to each review issue**
[Menubar review](https://github.com/w3c/aria-at/issues/54)
[Checkbox review](https://github.com/w3c/aria-at/issues/52)
[Combobox review ](https://github.com/w3c/aria-at/issues/53)

**Comment by spectranaut** [comment]
@Yohta89 is there things that still need to be addressed that you haven't gotten the chance to bring up in a meeting?

**Comment by Yohta89** [comment]
They are mostly covered, and I'll bring them up as needed!
The issue was to help us streamline the meeting on 2/26, so I'll be closing this.
