### ISSUE TITLE
Feedback: "Open a Modal Dialog in reading mode" (Modal Dialog Example, Test 1)

### ISSUE THREAD

**Issue by AlyssaGourley** [w3c/aria-at#895]
## Description of Behavior
When pressing SPACE or ENTER to open the modal dialog, JAWS reads, "Add Delivery Address  dialog  
Street: City: State: Zip: Special instructions: For example, gate code or other information to help the driver find you
Street:  Edit  Has Popup." 
I would consider this unnecessarily verbose, because I would not expect the screen reader to read out all the fields and then repeat the field my cursor is in. I would expect to encounter only the information for the "Street" field because that is the one in focus.

 

## Test Setup

- Test File: [test-01-open-a-modal-dialog-reading-jaws.collected.html](https://aria-at.netlify.app/tests/modal-dialog/test-01-open-a-modal-dialog-reading-jaws.collected.html)
- AT: JAWS (version 2023.2212.23)
- Browser: Chrome (version 110.0.0)

## Review Conflicts for "Open a Modal Dialog in reading mode"

1.  ### Unexpected Behaviors for "Space" Command
    
    *   Tester IsaDC recorded output "Add Delivery Address  dialog Street: City: State: Zip: Special instructions: For example, gate code or other information to help the driver find you Street: Edit Type in text." and noted no unexpected behavior.
    *   Tester AlyssaGourley recorded output "Add Delivery Address  dialog  Street: City: State: Zip: Special instructions: For example, gate code or other information to help the driver find you Street:  Edit  Has Popup" and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".

**Comment by jscholes** [comment]
@AlyssaGourley Thanks for reporting!  This was an oversight in another tester's results that has now been resolved, so the results match.
