### ISSUE TITLE
Feedback: "Navigate to the last checked radio button in a group" (Radio Group Example Using aria-activedescendant, Test 8)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#930]
## Description of Behavior

When using the command: Shift+Control+option+command+J, VoiceOver navigates to the "Run test setup" which is the next control.  I retested 4 times.  If I press the same command again the VoiceOver navigates to the last radio button.  The VoiceOver command seems broken or the test is causing a weird issue.
 
## Test Setup

- Test File: [test-08-navigate-to-the-last-checked-radio-button-in-a-group-interaction-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/radiogroup-aria-activedescendant/test-08-navigate-to-the-last-checked-radio-button-in-a-group-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version 13.3)
- Browser: Chrome (version 112.0.0)

**Comment by jscholes** [comment]
@jha11y In line with discussion in the CG meeting of April 13, please rerun the tests containing this command, and record "incorrect output" if you can reproduce the unexpected behaviour.
