### ISSUE TITLE
Feedback: "Navigate forwards to an unchecked radio button" (Radio Group Example Using aria-activedescendant, Test 10)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#933]
## Description of Behavior

(See recorded  results below)

## Test Setup

- Test File: [test-10-navigate-forwards-to-an-unchecked-radio-button-interaction-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/radiogroup-aria-activedescendant/test-10-navigate-forwards-to-an-unchecked-radio-button-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version 13.3)
- Browser: Chrome (version 112.0.0)

**Comment by mcking65** [comment]
@IsaDC 

I don't see output or a description of the issue.

**Comment by IsaDC** [comment]
@mcking65  Sorry about that, this test has no conflicts.
