### ISSUE TITLE
Feedback: "Open a menu in reading mode" (Navigation Menu Button, Test 10)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#958]
## Description of Behavior

Hi @AlyssaGourley , I think there is some confusion between the roles menu and menu item.
I can see that we got the same output, but NVDA is not conveying the role of menu item.
Could you please update your results when you have a chance?
Thank you.

 

## Test Setup

- Test File: [test-10-open-a-menu-reading-nvda.collected.html](https://aria-at.netlify.app/tests/menu-button-navigation/test-10-open-a-menu-reading-nvda.collected.html)
- AT: NVDA (version 2023.1 )
- Browser: Firefox (version 113.0.0)

## Review Conflicts for "Open a menu in reading mode"

1.  ### Assertion Results for "Space" Command and "Role of the focused item, 'menu item', is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "W3C Home Page 1 of 6 WAI-ARIA Quick Links menu" and marked assertion as passing.
    *   Tester IsaDC recorded output "W3C Home Page 1 of 6 WAI-ARIA Quick Links menu" and marked assertion as failing with no output.
2.  ### Assertion Results for "Enter" Command and "Role of the focused item, 'menu item', is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "W3C Home Page 1 of 6" and marked assertion as passing.
    *   Tester IsaDC recorded output "W3C Home Page 1 of 6" and marked assertion as failing with no output.

**Comment by AlyssaGourley** [comment]
Interesting. I understand the confusion on the first one but I'm not sure why I passed the one for "menu item" with ENTER key. I'll fix these.
