### ISSUE TITLE
Inconsistent announcement of W3C Quick Links Menu "Open a menu in interaction mode" (Navigation Menu Button, Test 11)

### ISSUE THREAD

**Issue by AlyssaGourley** [w3c/aria-at#959]
## Description of Behavior
When using SPACE, ENTER, and DOWN-ARROW, NVDA did not consistently announce the "WAI-ARIA Quick Links menu" information. I've tested each multiple times and sometimes it would announce all the information but more often it would not.
Side note: the first two conflicts I've actually resolved and updated so I'm not sure why they're not showing as updated. Notes are below in the conflicts section.

## Test Setup

- Test File: [test-11-open-a-menu-interaction-nvda.collected.html](https://aria-at.netlify.app/tests/menu-button-navigation/test-11-open-a-menu-interaction-nvda.collected.html)
- AT: NVDA (version 2023.1 )
- Browser: Firefox (version 114.0.0)

## Review Conflicts for "Open a menu in interaction mode"

1.  ### Assertion Results for "Space" Command and "Role 'menu' is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "W3C Home Page 1 of 6 WAI-ARIA Quick Links menu" and marked assertion as passing.
    *   Tester IsaDC recorded output "space W3C Home Page 1 of 6" and marked assertion as failing with no output.
    * Note: I actually fixed this one so I'm not sure why the result didn't update.
2.  ### Assertion Results for "Space" Command and "Name 'WAI-ARIA Quick Links' is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "W3C Home Page 1 of 6 WAI-ARIA Quick Links menu" and marked assertion as passing.
    *   Tester IsaDC recorded output "space W3C Home Page 1 of 6" and marked assertion as failing with no output.
    *     Note: I updated this one as well so I'm not sure why the result didn't update.

3.  ### Assertion Results for "Down Arrow" Command and "Role 'menu' is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "W3C Home Page 1 of 6" and marked assertion as failing with no output.
    *   Tester IsaDC recorded output "W3C Home Page 1 of 6 WAI-ARIA Quick Links menu" and marked assertion as passing.
    * Note: I could not get consistent announcement of the "WAI-ARIA Quick Links menu." I got it to announce once but in subsequent tests I could not get NVDA to announce that.
4.  ### Assertion Results for "Down Arrow" Command and "Name 'WAI-ARIA Quick Links' is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "W3C Home Page 1 of 6" and marked assertion as failing with no output.
    *   Tester IsaDC recorded output "W3C Home Page 1 of 6 WAI-ARIA Quick Links menu" and marked assertion as passing.
    * Note: Again, I could not get a consistent announcement of the "WAI-ARIA Quick Links menu" " information.

**Comment by IsaDC** [comment]
Results matched after rerunning this test.
