### ISSUE TITLE
JAWS Feedback: "Check a radio button in interaction mode" (Radio Group Example Using aria-activedescendant, Test 26, 10-04-2023)

### ISSUE THREAD

**Issue by RFischer-FS** [w3c/aria-at#966]
The review page for this element needs additional clarification. 

1) The test result and the details seem to conflict with each other. For test 17. the overall test result says: Pass, but the tables with details list failing commands. James explained the reason behind this presentation, but the chosen presentation could be clearer.
2) If a command is listed as failing due to unexpected behaviors, it is difficult to understand why the output is considered unexpected. This is the case for tests 17.,18.,19.,20., 25. and 26. We would like to get further insights into the reasoning behind the unexpected behaviors.

**Comment by mcking65** [comment]
@RFischer-FS 

We now have a new version of this test plan and more clear presentation of results. Please review again.

**Comment by mcking65** [comment]
closing as fixed
