### ISSUE TITLE
Change results collection form to support pass/fail assertion verdicts

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#969]
This issue is one element of the plan documented in #961 to migrate from 3 assertion verdicts (good/no output/incorrect output) to two verdicts (pass/fail).

In the results collection form, there is a three-column table of assertions and radio buttons for recording the verdicts of each assertion. Replace the table with a `fieldset` containing checkbox elements with assertion statements as labels.

This specification assumes this change is being made coincident with or after w3c/aria-at-app#743. Thus, it specifies [Test Format V2](https://github.com/w3c/aria-at/wiki/Test-Format-Definition-V2) values.

The `legend` of the `fieldset` is composed of the following strings:

`assertionResponseQuestion + " " + commandSpecificationString + "?"`

Where:
* `assertionResponseQuestion` is the `name` property of an object in the `testPlanStrings` array in `support.json`
* `commandSpecificationString` is a command or command sequence string with any associated settings in parentheses as described in #977.

Using values from `support.json` in the `slider-refactor` branch and commands and assertions from the `jaws-commands.csv` in the same branch, here is example code:

~~~
<fieldset>
  <legend>Which statements are true about the response to Down Arrow then Down Arrow (virtual cursor active)?</legend>
  <label>
    <input type="checkbox" name="assertion1">
    Role 'slider' is conveyed
  </label>
  <label>
    <input type="checkbox" name="assertion2">
    Name 'Red' is conveyed
  </label>
  <label>
    <input type="checkbox" name="assertion3">
    Value '128' is conveyed
  </label>
  <label>
    <input type="checkbox" name="assertion4">
    Orientation 'horizontal' is conveyed
  </label>
  <label>
    <input type="checkbox" name="assertion5">
    Minimum value '0' is conveyed
  </label>
  <label>
    <input type="checkbox" name="assertion6">
    Maximum value '255' is conveyed
  </label>
</fieldset>
~~~

**Comment by mcking65** [comment]
@jscholes We will discuss at Tuesday meeting; please look at attached HTML before then if possible.

**Comment by jscholes** [comment]
@mcking65 I feel very strongly that radios are not an optimal direction, and also that the assertions tables for testers are not a helpful construct to keep going forward.  I've expanded on my reasoning in https://github.com/w3c/aria-at/issues/974#issuecomment-1676029956, but let's discuss more this coming Tuesday if possible.

**Comment by mcking65** [comment]
@jscholes 

The specification for assertion verdict collection is now a set of checkboxes. Please re-review specification in top comment.

**Comment by ccanash** [comment]
Closing as this has been released
