### ISSUE TITLE
Support reporting that an AT did not respond to a command

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#973]
#### Problem

If an AT does not respond to a command, the form for collecting responses does not provide a way of indicating that a response did not occur. The input field where users type the output string from a screen reader is required.

#### Proposed solution

Adjacent to the edit field for AT response, provide a checkbox with label "AT_NAME responded to COMMAND_NAME" that is checked by default.

When the checkbox is checked, the text field for AT response is required. If the checkbox is not checked, the response text field is set to an empty state and disabled.

**Comment by ccanash** [comment]
Hi @mcking65, we were triaging this task and realized we already implemented something similar and deployed it to production [here](https://github.com/w3c/aria-at-app/pull/751). We wanted to confirm with you if we should implement what is described in this task and/ or if we should make changes to what is already in production. Thank you

**Comment by mcking65** [comment]
The production implementation fully satisfies this requirement.
