### ISSUE TITLE
Design replacement for keys.mjs that replaces explicit definition of key commands to a more dynamic model

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#976]
Note: this is intended to accompany the move to v2 of the test format, mostly being defined in issue #974.

#### Background
Currently, keyboard commands to be used by all tests are defined in `tests/resources/keys.mjs`, with this file not being test-plan-specific.  This is a JavaScript module file, defining all keyboard commands as separate constants.  The value of the constant is a human-readable string shown to testers, and the constant names are used within test data to reference the commands.  For example:

`export const CTRL_HOME = "Control+Home";`

If writing a test which used Control+Home as one of its commands, the constant name `CTRL_HOME` would be added to the relevant row/column of the appropriate `commands.csv` file.  At test build time, this constant would be looked up, and the human-readable value `"Control+Home"` would be presented in the instructions for human testers.

The categories of commands tracked in `keys.mjs` today can be broken down as follows:
* Single keys, e.g. A, Enter, Delete.
* Key combinations with one or more modifier(s) plus a single key, like Control+Home, Control+Option+Left.
* Command sequences as a single command, e.g. "Control+Home followed by Down Arrow".  This is a holdover from the days when the test format didn't support concatenating several commands together as a sequence, and will not be needed in test format v2.
* Multiple commands intended to be carried out separately rather than in a consecutive sequence, e.g. `const C_AND_SHIFT_C                    = "C / Shift+C"`.  This is a holdover from when testing tasks were less granular, for instance a tester would be instructed to navigate to a combobox using both forwards and backwards directional commands in the same test rather than separate ones.  It will not be needed in test format v2.

#### Problems with the Current Approach
* Using a JavaScript module file conflates code and data, and complicates interop with non-JavaScript tools.
* There is no rhyme or reason to how the file is laid out right now: the first command is Control+Home, the first single command is on line 7, the alphabet doesn't start until line 75, and categories of command are interleaved.
* The file has many inconsistencies:
	* Most commands use "Control" as the name of that modifier, but "Ctrl" is also used in one case.
	* Most commands use only "Insert" as the modifier for Windows screen reader commands, but some mention "CapsLock" as an alternative which contradicts instructions to use default screen reader settings.
	* Some commands are unnecessarily defined more than once.
	* For some commands but not all, whitespace has been added in an attempt to vertically align the values on the right-hand side of equals.  This is frankly too much effort to maintain manually, a disproportionate challenge for blind developers, and makes the file frustrating to read on a braille display.
* Test writers must constantly check whether particular commands are defined, and add them if not.  This is made more frustrating by the various inconsistencies already noted.
* If a test writer is concurrently working on test plans across branches, and the same command is needed in more than one of those plans, merge conflicts can happen when the command is added to two or more copies of the file.
* Many constant names are long because of the number of modifiers that they contain, reducing the readability of the file for everyone but particularly with a screen reader.  E.g. `export const CTRL_OPT_CMD_J_AND_SHIFT_CTRL_OPT_CMD_J = "Control+Option+Command+J / Shift+Control+Option+Command+J";`.

#### Proposal
Not trying to solve for future needs like touch gestures, I claim that the following assertions are true for keyboard commands:
* Each command consists of zero or more modifiers, and exactly one non-modifier key.
* Sequences are now formally supported within the test format, and do not need to be represented as resources.
* There is a small number of test plans still relying on compound, multi-direction commands, but these plans are outdated and badly in need of modification.  As such, these also do not need to be represented as resources given that all test plans will be rewritten for format v2.
* Some modifiers, or combinations of modifiers, have common aliases in speech and the wider community, e.g. JAWS+Tab, NVDA+L, VO+Shift+M.

With these assertions in mind, I propose five main changes:
1. Use a JSON file instead of a JavaScript module.
2. Include all standard modifiers, screen reader modifiers, and non-modifier keys that tests will feasibly need now and into the future.
3. Provide aliases for commonly used modifiers, combinations of modifiers, and single keys, solely to make test writing easier and less verbose.  These aliases are not presented to human testers.
4. Provide name overrides for some keys and modifiers where necessary, likewise to make test writing less verbose while providing readable strings to testers.
5. Compose commands in test data files directly, rather than relying on every single command to have a defined name.

##### JSON File
`keys.json` is a dictionary with six top-level keys:
* `"keys"`: an array of IDs of all single keys that tests might feasibly need, now and reasonably into the future.  This can be generated from e.g. the HID standard.
* `"keyAliases"`: a dictionary mapping short IDs to canonical IDs in the `"keys"` section, e.g. `"Del": "Delete"`.
* `"keyNames"`: a dictionary mapping canonical IDs in the `"keys"` section to overridden human-friendly names.  For example, the ID `"Down"` is mapped to the string `"Down Arrow"`, with a space between the words.  An entry is only necessary in this dictionary for keys where the ID is not considered sufficiently readable.
* `"modifiers"`: an array of IDs of all standard and screen reader modifiers that tests might feasibly need, now and reasonably into the future.
* `"modifierAliases"`: a dictionary mapping short IDs to a combination of one or more canonical IDs from the `"modifiers"` section.  For instance, `"JAWS": "Ins"` and `"VO": "Ctrl+Opt"`.
* `"modifierNames"`: a dictionary mapping canonical IDs in the `"modifiers"` section to overridden human-friendly names.  For example, the ID `"Ctrl"` is mapped to the string `"Control"`, `"Ins"` to `"Insert"`, etc.  An entry is only necessary in this dictionary for keys where the ID is not considered sufficiently readable.

An example JSON file is at the end of this issue that should fulfill all current needs, and may not need to be updated by a test writer for many months.

##### Command Composition
Within each `*-commands.csv` file, commands can be composed directly based on values from `keys.json`.  Specifically, a valid command composition consists of the following portions:
* zero or more modifier alias IDs, joined with a plus;
* zero or more modifier IDs, joined with a plus; and
* exactly one single key ID, or exactly one key alias ID.

Portions are also joined with a plus.  It is suggested that this ordering be mandatory, i.e. the last portion is always a single key ID, or a single key alias ID, and modifier aliases come before modifiers for increased readability.  Example valid commands could be:
* `C`
* `Shift+C`
* `NVDA+Up`
* `JAWS+Tab`
* `VO+Shift+M`

It is an error to have a command that:
* starts with a plus;
* ends with a plus;
* consists of only modifier IDs and/or modifier alias IDs;
* ends with a modifier ID or modifier alias ID;
* has a single key ID before a modifier ID or modifier alias ID;
* contains one or more modifier, modifier alias, single key, and/or single key alias IDs which are not found in the relevant section of `keys.json`; and
* uses key and/or modifier names instead of IDs (e.g. `"Insert+Up Arrow"` is not valid).

During the test build process, modifier and key alias IDs must be expanded, and the resulting modifier and key IDs must then be looked up in the `"modifierNames"` and `"keyNames"` section, respectively.  If a name override is not specified for a modifier ID or key ID, the ID must be used as is.  Alias ID expansion must happen recursively, because an alias ID could reference another alias ID of the same type (although it is an error for a modifier alias ID to reference the alias ID for a key and vice versa).

###### Working example
* `voiceover_macos-commands.csv` contains a command that reads: `"VO+Shift+Up"`.
* The modifier ID alias `"VO"` expands to the string `"Ctrl+Opt"`.
* The modifier IDs from the previous step, `"Ctrl"` and `"Opt"`, have name overrides in the `"modifierNames"` section of `"Control"` and `"Option"`, respectively.
* The modifier ID `"Shift"` is not an alias ID, nor does it have a name override.  It is used as is.
* The key ID, `"Up"`, has a name override in the `"keyNames"` section of `"Up Arrow"`.
* The resulting human-readable command is `"Control+Option+Shift+Up Arrow"`.

##### Example `keys.json` File
```
{
	"modifiers": [
		"Ctrl",
		"Opt",
		"Cmd",
		"Shift",
		"Alt",
		"Win",
		"Ins"
	],
	"modifierAliases": {
		"JAWS": "Ins",
		"NVDA": "Ins",
		"VO": "Ctrl+Opt"
	},
	"modifierNames": {
		"Ctrl": "Control",
		"Opt": "Option",
		"Cmd": "Command",
		"Win": "Windows",
		"Ins": "Insert"
	},
	"keys": [
		"A",
		"B",
		"C",
		"D",
		"E",
		"F",
		"G",
		"H",
		"I",
		"J",
		"K",
		"L",
		"M",
		"N",
		"O",
		"P",
		"Q",
		"R",
		"S",
		"T",
		"U",
		"V",
		"W",
		"X",
		"Y",
		"Z",
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"0",
		"Enter",
		"Escape",
		"Backspace",
		"Tab",
		"Space",
		"Dash",
		"Equals",
		"LeftBracket",
		"RightBracket",
		"Backslash",
		"Pound",
		"Semicolon",
		"Apostrophe",
		"Grave",
		"Comma",
		"Period",
		"Slash",
		"CapsLock",
		"F1",
		"F2",
		"F3",
		"F4",
		"F5",
		"F6",
		"F7",
		"F8",
		"F9",
		"F10",
		"F11",
		"F12",
		"ScrollLock",
		"Pause",
		"Home",
		"End",
		"PageUp",
		"PageDown",
		"Delete",
		"Left",
		"Right",
		"Up",
		"Down",
		"NumLock",
		"NumpadSlash",
		"NumpadAsterisk",
		"NumpadMinus",
		"NumpadPlus",
		"NumpadEnter",
		"Numpad1",
		"Numpad2",
		"Numpad3",
		"Numpad4",
		"Numpad5",
		"Numpad6",
		"Numpad7",
		"Numpad8",
		"Numpad9",
		"Numpad0",
		"NumpadPeriod"
	],
	"keyAliases": {
		"Del": "Delete"
	},
	"keyNames": {
		"LeftBracket": "Left Bracket",
		"RightBracket": "Right Bracket",
		"CapsLock": "Caps Lock",
		"ScrollLock": "Scroll Lock",
		"PageUp": "Page Up",
		"PageDown": "Page Down",
		"Left": "Left Arrow",
		"Right": "Right Arrow",
		"Up": "Up Arrow",
		"Down": "Down Arrow",
		"NumLock": "Num Lock",
		"NumpadSlash": "Numpad Divide",
		"NumpadAsterisk": "Numpad Multiply",
		"NumpadMinus": "Numpad Minus",
		"NumpadPlus": "NumpadPlus",
		"NumpadEnter": "Numpad Enter",
		"Numpad1": "Numpad 1",
		"Numpad2": "Numpad 2",
		"Numpad3": "Numpad 3",
		"Numpad4": "Numpad 4",
		"Numpad5": "Numpad 5",
		"Numpad6": "Numpad 6",
		"Numpad7": "Numpad 7",
		"Numpad8": "Numpad 8",
		"Numpad9": "Numpad 9",
		"Numpad0": "Numpad 0",
		"NumpadPeriod": "Numpad Decimal"
	}
}
```

@mcking65 and @IsaDC, let me know what you think!

**Comment by mcking65** [comment]
@jscholes 

This is a fabulous direction! I do want to consider making it a "commands.json" and allow for gestures to be defined in the future. Now that V2 of the format completely separates testing tasks from modes/settings and instead ties settings to commands, there is nothing stopping us from adding a voiceover_iOS commands file to any existing test plan.

I want to spend a little more time on some of the details. I might have a couple of suggestions.

Overall, this is fantastic!!!!!!! I love how we can just write commands and not have to be constantly looking up the name of constants! It has been a constant source of frustration. constant, constant, constant ...

**Comment by mcking65** [comment]
@jscholes 

I'd like to propose some ideas that simplify the json and may simplify the code consuming it. This might possibly remove the need to do any recursive processing.

1. Remove keyNames and store the key names as values for each key ID.
2. Remove modifierNames and store the modifier names as values for each modifier ID.
3. Add aliases for modifiers that enable test authors to use either the ID form or the name form, e.g., an alias of "Command" for the ID "Cmd".
4. Store it in a file named `tests/commands.json`. I suggest calling it `commands.json` instead of `keys.json` because I believe we could eventually include gestures in the same file.

With these changes, to me it seems easier to read and understand, which helps with maintenance. For example, it is easier to ensure that there is a name where there needs to be a name because all IDs have a name value. That should also lead to simpler rendering logic.

Here is the json you provided with these changes. What do you think?

~~~
{
  "modifiers": {
    "Alt": "Alt",
    "Opt": "Option",
    "Shift": "Shift",
    "Ctrl": "Control",
    "Cmd": "Command",
    "Win": "Windows",
    "Ins": "Insert"
  },
  "modifierAliases": {
    "JAWS": "Ins",
    "NVDA": "Ins",
    "VO": "Ctrl+Opt",
    "insert": "Ins",
    "Control": "Ctrl",
    "Option": "Opt",
    "Command": "Cmd",
    "Windows": "Win"
  },
  "keys": {
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "H": "H",
    "I": "I",
    "J": "J",
    "K": "K",
    "L": "L",
    "M": "M",
    "N": "N",
    "O": "O",
    "P": "P",
    "Q": "Q",
    "R": "R",
    "S": "S",
    "T": "T",
    "U": "U",
    "V": "V",
    "W": "W",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "0": "0",
    "Dash": "Dash",
    "Equals": "Equals",
    "Grave": "Grave",
    "LeftBracket": "Left Bracket",
    "RightBracket": "Right Bracket",
    "Backslash": "Back slash",
    "Semicolon": "Semicolon",
    "Apostrophe": "Apostrophe",
    "Comma": "Comma",
    "Period": "Period",
    "Slash": "Slash",
    "Escape": "Escape",
    "Backspace": "Backspace",
    "Tab": "Tab",
    "CapsLock": "Caps Lock",
    "Enter": "Enter",
    "Space": "Space",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
    "ScrollLock": "Scroll Lock",
    "Pause": "Pause",
    "Home": "Home",
    "End": "End",
    "PageUp": "Page Up",
    "PageDown": "Page Down",
    "Delete": "Delete",
    "Left": "Left Arrow",
    "Right": "Right Arrow",
    "Up": "Up Arrow",
    "Down": "Down Arrow",
    "NumLock": "Num Lock",
    "NumpadSlash": "Numpad Slash",
    "NumpadAsterisk": "Numpad Asterisk",
    "NumpadMinus": "Numpad Minus",
    "NumpadPlus": "Numpad Plus",
    "NumpadEnter": "Numpad Enter",
    "Numpad1": "Numpad 1",
    "Numpad2": "Numpad 2",
    "Numpad3": "Numpad 3",
    "Numpad4": "Numpad 4",
    "Numpad5": "Numpad 5",
    "Numpad6": "Numpad 6",
    "Numpad7": "Numpad 7",
    "Numpad8": "Numpad 8",
    "Numpad9": "Numpad 9",
    "Numpad0": "Numpad 0",
    "NumpadPeriod": "Numpad Period"
},
  "keyAliases": {
    "Del": "Delete"
  }
}
~~~

**Comment by mcking65** [comment]
@jscholes 

I'd like to propose  that the names of letter keys should be lowercase. If the instruction to a tester is to use the command "F", that could be interpreted as "Shift+f". In fact, that is how I would expect a VoiceOver user to interpret it because Apple is very consistent about case in their documentation and in the commander user interface where you customize the quick nav commands.

I noticed that the NVDA manual is also consistent with specifying that the command for next form field is "f", not "F".

Vispero writes all their commands in allcaps all the time, crating potential for confusion within their documentation. You have  to read the content outside the list of commands. In the list of web quick keys, Vispero doesn't explicitly list a command for "Previous form field". You have to read outside the table to find out to use Shift.

**Comment by jscholes** [comment]
@mcking65 Thanks for the feedback and updated example!  Here are my lengthy comments.

> Remove `keyNames` and store the key names as values for each key ID.

The `keyNames` section was intended to avoid needing to provide explicit key names when the IDs could be considered sufficient.  Of the 94 key IDs, 67 of them didn't require a name in my view (just over 71%).  Meanwhile, from a development perspective, looking something up in an object and falling back to another value if it doesn't exist is a common paradigm.

Having said that, I say this only to document my reasoning behind the original proposal.  Ultimately, the aim of test writers not needing to frequently modify this file still stands, and I am okay with explicitly defining a name for all key and modifier IDs... particularly since you already did the work.

Note that "backslash" shouldn't contain a space.  It is a single word, and the space changes the inflection with which speech synths (including Eloquence) pronounce it quite significantly.

> Add aliases for modifiers that enable test authors to use either the ID form or the name form, e.g., an alias of "Command" for the ID "Cmd".

This was actually how I originally specced it out, before deciding to separate the concept of aliases for test writers from overridden names for human readers.

The problem with allowing a test writer to use multiple forms is that different people will have their own idea of what is most readable to them, leading to inconsistencies in how tests are written.  This is probably not that important in the grand scheme of things, but my instinct was to opt (or should that be option!) for an opinionated design with predictable naming.  Grepping/searching test files becomes more complex if there is a possibility of using different names for the same thing, for instance.

However, I should also acknowledge that the original proposal allowed for this in some form.  It would be up to the test writer whether they used `"Ins+Tab"`, `"NVDA+Tab"` or `"JAWS+Tab"`, and similarly for `"Ctrl+Opt+Right"` vs `"VO+Right"`.  The aim there was to allow commands using those modifiers to be added to a test without being screen-reader-specific, with the expectation being that the aliases would be used most of the time.

So, personally I would prefer to keep this how it was, and only encourage one form within test data while allowing for a small amount of flexibility when warranted.

> Make letter key names lower case (see next comment in this thread for reasoning)

The internal style guide we use at PAC requires all key and modifier names to be written in title case, i.e. the first letter of each key is always capitalised even if it is the only one.  This is primarily driven by:
* how keyboard shortcuts are written in Microsoft Windows; and
* the fact that single letters are capitalised when used as single words in written English.

Again, I raise this only to explain why the proposal was made as it was.  Looking at the specific comments...

> If the instruction to a tester is to use the command "F", that could be interpreted as "Shift+f". In fact, that is how I would expect a VoiceOver user to interpret it because Apple is very consistent about case in their documentation and in the commander user interface where you customize the quick nav commands.

I don't have any data as to how different users would interpret an uppercase single-letter F on its own.  For me personally, the idea of adding a modifier just because of how it's written seems odd.  Meanwhile, documenting keys in this way for an audience who primarily consumes the information through speech does not seem ideal; there is often no immediate means of distinguishing between two characters based on case alone without manually navigating through the text.

> I noticed that the NVDA manual is also consistent with specifying that the command for next form field is "f", not "F".

The NVDA manual also includes compound key names like "Down Arrow" as single words ("downArrow"), inconsistently uppercases the "NVDA" modifier without uppercasing any others presumably so it will be spoken correctly, and doesn't use a space after "numpad".  These approaches have an air of being generated from code about them, despite key and modifier identifiers not being case-sensitive internally within NVDA itself.

I don't think these are large problems, and wouldn't suggest that the quality of the NVDA manual is low because of them.  But we will be departing from NVDA's styling in several ways regardless of how we treat single letters.

> Vispero writes all their commands in allcaps all the time

The readability issues with all-caps text are well known, so this is unfortunate.

I'm not sure where this leaves us.  The writer in me does not like the idea of styling single letters in lower case, and I don't find the examples being cited for the decision to be particularly compelling.  On the other hand, these are only my personal opinions, and not including Shift does save a bit of typing.

If we do go with lower case for single characters, I would be inclined to switch to that styling for all key and modifier names too, and definitely for key and modifier IDs so that test writers never have to specify anything in upper case.

> I suggest calling it `commands.json` instead of `keys.json` because I believe we could eventually include gestures in the same file.

I agree with this.

**Comment by mcking65** [comment]
@mcking65 wrote:

> Remove `keyNames` and store the key names as values for each key ID.

@jscholes wrote:
>Ultimately, the aim of test writers not needing to frequently modify this file still stands, and I am okay with explicitly defining a name for all key and modifier IDs... particularly since you already did the work.

OK, thanks.  Overall, to me the consistency feels like simplicity. It is fewer objects to reference and one less conditional statement to document and implement.

@jscholes wrote:

> Note that "backslash" shouldn't contain a space. It is a single word, and the space changes the inflection with which speech synths (including Eloquence) pronounce it quite significantly.

Oh,I'll correct that.

@mcking65 wrote:

> Add aliases for modifiers that enable test authors to use either the ID form or the name form, e.g., an alias of "Command" for the ID "Cmd".

@jscholes  wrote:

> This was actually how I originally specced it out, before deciding to separate the concept of aliases for test writers from overridden names for human readers.
> 
> The problem with allowing a test writer to use multiple forms is that different people will have their own idea of what is most readable to them, leading to inconsistencies in how tests are written. This is probably not that important in the grand scheme of things, but my instinct was to opt (or should that be option!) for an opinionated design with predictable naming. Grepping/searching test files becomes more complex if there is a possibility of using different names for the same thing, for instance.

If we want to be opinioniated and require consistency for those reasons, I recommend removing the aliases. By design, they give alternatives that create inconsistency.

One advantage of aliases is that I don't have to remember the details of how the IDs are written. Was it "Cmd" or "Command". Well, since there is an alias, I don't care. I will write either and not have to worry about one more possible error coming out of the build script.

Of course, another value is shorthand. "VO" is much shorter than "Ctrl+Opt".

So, if we are going to have some aliases, I don't see any reason to not allow addition of any alias that has any potential utility. We get more utility with no additional disadvantage.

So, unless there is a disadvantage to more and more aliases that I'm not grasping, my recommendation is choose one of these:
* Option A: keep all the aliases I added and don't hesitate to add more as useful ideas arise.
* Option B: remove all the aliases.

I kind of lean toward option A, but I could go either way if you think consistency is particularly valuable in this regard. If consistency is that valuable, then we might also consider conventions for the order of modifiers.

@mcking65 wrote:

> Make letter key names lower case (see next comment in this thread for reasoning)
> 
> > If the instruction to a tester is to use the command "F", that could be interpreted as "Shift+f". In fact, that is how I would expect a VoiceOver user to interpret it because Apple is very consistent about case in their documentation and in the commander user interface where you customize the quick nav commands.

@jscholes wrote:

> I don't have any data as to how different users would interpret an uppercase single-letter F on its own. For me personally, the idea of adding a modifier just because of how it's written seems odd. Meanwhile, documenting keys in this way for an audience who primarily consumes the information through speech does not seem ideal; there is often no immediate means of distinguishing between two characters based on case alone without manually navigating through the text.

To me, it seems completely natural that if you see Upper case "F" and are following instructions, you would type "Shift+f" because that is how you get an upper case "F". You have to do that if you are reading the VoiceOver help. It is just like the quick nav key for previous level 1 heading is "!".

However, I completely agree that it would be easier for everyone, especially screen reader users, if the ARIA-AT instructions and reports were to display "Shift+f" instead of uppercase "F" and "Shift+1" instead of "!".

When we are testing and reporting on the command lowercase "f", there are potential problems if the instructions and reports display uppercase "F". Given how VoiceOver is documented and how its UI works, people at Apple or VoiceOver users could legitimately report errors in the instructions or reports if we are displaying uppercase "F" but showing instructions or reports that are related to lowercase "f".

If we consistently display lowercase "f for navigating to the next form field and "Shift+f" for navigating to the previous form field, it is indisputably accurate regardless of what screen reader is in use.

@jscholes wrote:

>I'm not sure where this leaves us. The writer in me does not like the idea of styling single letters in lower case, 

Granted, what I am suggesting is stylistically unconventional, at least in prose, and is understandably unappealing because of such conventions. However, there is one thing we could and probably should do to address that -- wrap all keyboard commands in <kbd> tags. We have that as part of the editorial standard for APG.

>On the other hand, these are only my personal opinions, and not including Shift does save a bit of typing.

To be clear, we still would be typing the word "Shift". I am recommending that the instructions and reports show lowercase "f" for navigate forward and "Shift+f" for navigating backward.

@jscholes wrote:

> If we do go with lower case for single characters, I would be inclined to switch to that styling for all key and modifier names too, and definitely for key and modifier IDs so that test writers never have to specify anything in upper case.

I don't think the names should all be lowercase. That would defy conventions even for `<kbd>` elements. For example, the value for the dictionary key "Cmd" should be "Command".

However, I'm all about removing all trouble related to case for test authors. Since every key has a name, we have two options:
1. your suggestion of making all the dictionary keys lowercase.
2. Specify that the dictionary is searched in a case-insensitive manner. I was considering adding this to the spec as a way to reduce the frequency of build errors.
3. 
Actually, we could do both of these things.

**Comment by jscholes** [comment]
@mcking65:

> One advantage of aliases is that I don't have to remember the details of how the IDs are written. Was it "Cmd" or "Command". Well, since there is an alias, I don't care. I will write either and not have to worry about one more possible error coming out of the build script.

This is fair, and illustrates that we will be making a compromise no matter which way we go on this.  I am okay with that compromise leaning more towards test writing than test modification, i.e. option A.

> It is just like the quick nav key for previous level 1 heading is "!".

The command for previous level 1 heading is only an exclamation mark if Shift+1 maps to that particular symbol on a person's keyboard. There are many users around the world for whom that will not be the case, despite them still wishing to consume documentation written in English.

Regardless, the aim of this conversation is not to assess the documentation practices of third parties, and we won't be following such a pattern as you've indicated.  If you feel that upper-case letters without Shift may cause any level of confusion, I am happy with us trying to avoid it.

**Comment by mcking65** [comment]
This has been implemented in the repository.
