### ISSUE TITLE
Feedback: "Read information about a menu item" (Action Menu Button Example Using aria-activedescendant, Test 16)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#981]
## Description of Behavior

I'm not sure if when the run test setup if the VoiceOver Cursor is actually focus on the Action 1 menu item.  It looks like it just has keyboard focus.

## Test Setup

- Test File: [test-16-read-information-about-menu-item-interaction-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/menu-button-actions-active-descendant/test-16-read-information-about-menu-item-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version 13.5)
- Browser: Safari (version 16.6.0)

**Comment by mcking65** [comment]
Clarified in meeting and test re-run
